- .travis.yml
> Use openssl

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
> Remove openssl dependency

- .travis.yml
> Add statically-linked version of bat

- src/main.rs
> Add option to specify language

- src/main.rs
* line number
* git modification marker
* file name
fix #5
> Add options to disable

- src/main.rs
> Hide everything but content for plain option style

- src/main.rs
> Open pager once for multiple files

- src/main.rs
- src/printer.rs
Code reviews would be appreciated!
closes #2
> Add support for reading from stdin

- src/assets.rs
- src/diff.rs
- src/main.rs
- src/printer.rs
Simple split of diffing and asset related functionality to their own modules. I can do some more cleanup if this is fine
> Split modules

- src/app.rs
- src/assets.rs
- src/main.rs
> add theme option

- assets/create.sh
The added repo is the "Julia" package on Package Control
> Add Julia highlighting support

- Cargo.lock
- Cargo.toml
- src/assets.rs
> Update to latest syntect, better error handling

- src/main.rs
- src/printer.rs
- tests/snapshots/output/changes,grid,header,numbers.snapshot.txt
- tests/snapshots/output/changes,grid,header.snapshot.txt
- tests/snapshots/output/changes,grid,numbers.snapshot.txt
- tests/snapshots/output/changes,grid.snapshot.txt
- tests/snapshots/output/changes,header,numbers.snapshot.txt
- tests/snapshots/output/changes,header.snapshot.txt
- tests/snapshots/output/changes,numbers.snapshot.txt
- tests/snapshots/output/changes.snapshot.txt
- tests/snapshots/output/full.snapshot.txt
- tests/snapshots/output/grid,header,numbers.snapshot.txt
- tests/snapshots/output/grid,header.snapshot.txt
- tests/snapshots/output/grid,numbers.snapshot.txt
- tests/snapshots/output/grid.snapshot.txt
- tests/snapshots/output/header,numbers.snapshot.txt
- tests/snapshots/output/header.snapshot.txt
- tests/snapshots/output/numbers.snapshot.txt
- tests/snapshots/output/plain.snapshot.txt
- tests/snapshots/sample.modified.rs
> Handle invalid utf8

- src/app.rs
- src/main.rs
> Skip '--quit-if-one-screen' for --paging=always

- src/app.rs
> Add -u and -n options

- src/assets.rs
- src/features.rs
- src/main.rs
I'm not sure if `features` is the best name for the module. Maybe you have a better idea. I did some minor cleanup for `list_languages`, but it still generates the same diff.
> Extract commands to functions

- src/output.rs
Adds support for the `BAT_PAGER` and `PAGER` environment variables.
If the pager is set to `less`, we pass the default arguments (`-FRX`) and set `LESSCHARSET=UTF-8`. If it is set to anything else, we simply launch the given command without passing any arguments or environment variables.
However, this can still be used to call `less` with different arguments by writing a small script
```bash
#!/bin/bash
less --tabs 4 -RF "$@"
```
that can be targeted by the `BAT_PAGER` variable.
> Add BAT_PAGER and PAGER environment variables

- src/features.rs
@tathanhdinh Unfortunatly, I need to revert your commit from #198 because it doesn't quite keep the same behavior. If there is a non-existing file, the following happens (the header is printed on STDOUT):
```
▶ bat non-existing
[bat error]: No such file or directory (os error 2)
───────┬───────────────────────────────────────────────────
│ File: non-existing
───────┼───────────────────────────────────────────────────
```
while it should just show the error message:
```
▶ bat non-existing
[bat error]: No such file or directory (os error 2)
```
This is due to the reordering of `File::open` and the `print_header` call.
> Revert "replace trait object BufRead by generic"

- .travis.yml
- ci/before_deploy.bash
- ci/before_install.bash
- ci/script.bash
> Add arm as a compile target

- assets/create.sh
- src/app.rs
- src/assets.rs
- src/main.rs
> Add new '--blank' option for 'bat cache --init'

- src/app.rs
> doc: mention BAT_THEME in help output

- src/app.rs
Slight amount of pasta, and can totally refactor if needed
Edit: Tested by diff'ing outputs of --style=plain and -p over multiple files. Should I add formal tests?
> #212 : added -p as an alias for --style=plain

- .gitmodules
Work towards #224 but @sharkdp is going to rebuild themes.bin
> Adds zenburn theme submodule

- src/main.rs
Fixes: https://github.com/sharkdp/bat/issues/232
> Fix panic when running `bat --list-languages | head`

- README.md
- appveyor.yml
- ci/before_deploy.ps1
- src/app.rs
- src/diff.rs
- tests/tester.rs
- tests/tests.rs
I'd like to execute bat in powershell.
> Windows version of bat

- .gitmodules
- assets/syntaxes/Cabal.sublime-syntax
addresses https://github.com/sharkdp/bat/issues/257
> Syntax highlighting for .cabal

- .gitmodules
- assets/syntaxes/Crystal.sublime-syntax
Add support for the Crystal language
> Add Crystal syntax

- src/printer.rs
> print additional newline if last line in input file was not terminated with a newline

- README.md
> Adds ansible install instructions for ansible to readme

- src/style.rs
> Disable wrapping when `--style` is plain

- README.md
My first contribution - let me know if this isn't clear or should go somewhere else.
> Fixes #273 - describes 'musl' builds.

- README.md
> Doc: add Chinese readme link

- src/app.rs
- src/clap_app.rs
- src/controller.rs
- src/line_range.rs
- tests/integration_tests.rs
> Allow for multiple line ranges

- src/app.rs
- src/clap_app.rs
- src/controller.rs
- src/output.rs
Close https://github.com/sharkdp/bat/issues/362
> Add --pager option

- ci/before_deploy.bash
- ci/before_deploy.ps1
> Temporarily disable shipping of shell completions

- src/app.rs
- src/clap_app.rs
- src/printer.rs
- src/terminal.rs
This is a work in progress for [#389](https://github.com/sharkdp/bat/issues/389).
It is not complete right now but awaiting confirmation that progress is being made in the right direction.
Thank you.
> WIP: Disable use of italics (by default)

- README.md
Work in progress to update the `README.md` file to include instructions for the config file. Addresses #377
> [WIP] README Updates for Config File 

- src/diff.rs
> Use Rust inclusive range (stable in 1.26)

- README.md
- doc/README-ja.md
I translated, so please check :wink:.
I also added a link to translate to Japanese in README.md.
Should you have any questions please feel free to contact us at anytime.
> add README-ja.md

- .gitmodules
- assets/syntaxes/HTML (Twig).sublime-syntax
> Add Twig syntax

- src/controller.rs
> Omit launching of pager if NO file exists

- .travis.yml
- README.md
- src/printer.rs
> Print ANSI-reset code before newline

- README.md
Correct instructions regarding Fedora Modular repos.
> Fix Fedora instructions in README

- build.rs
> Completely disable generation of shell completion files

- ci/before_deploy.bash
Hi! same as https://github.com/sharkdp/fd/pull/419; cheers!
> Add copyright file on Debian package

- .gitmodules
- assets/create.sh
- assets/syntaxes/fish.sublime-syntax
> Add syntax highlighting for fish shell

- .gitmodules
Add sublime-syntax file for a Jinja2
Example:
> Add Jinja2 syntax

- assets/create.sh
This fixes the reason why #661 was opened.
> Ensure submodules are updated before creating asset cache

- .gitmodules
Nice and popular theme, figured I'd ask if it could be included by default.
> Add Dracula theme

- README.md
> Add section concerning file encodings

- assets/README.md
- assets/syntaxes/Nim.sublime-syntax
> Add Nim syntax

- README.md
> Point to delta in usage-with-git section of README

- .gitmodules
> Properly add Twig submodule

- doc/README-ja.md
This line was already translated at 159f234.
> Remove the already translated line

- .gitmodules
Actually surprised this theme wasn't already there, would be very nice if it could be included.
Had to fork the official repo from a year-old commit before they switched to `.sublime-color-scheme`, hope it's okay.
> Add Nord theme

- doc/README-ja.md
The beginning part of untranslated was translated into Japanese text.
> Update Japanese README file

- src/bin/bat/app.rs
Closes #751.
I checked the tests but didn't found anything around the `--theme` option.
This is my very first PR in Rust, so apologies in advance if I managed to be non-idiomatic in just 7 lines of code :smile:
> Accept "default" as a theme

- LICENSE-MIT
- README.md
- doc/README-ja.md
- Copyright year have not been updated, so I updated this.
- Fixed invalid link to itself in the Japanese version README file.
- Added information about the license to README files to make it easier to check the terms of license.
> Update copyright year and add information about the license to README files

- examples/simple.rs
- src/bin/bat/app.rs
- src/bin/bat/main.rs
- src/diff.rs
- src/inputfile.rs
- src/printer.rs
> Allow for non-unicode filenames

- doc/README-ja.md
I added some japanese translation in doc/README-ja.md.
> Add ja-translation of Paging on Using bat on Windows

- README.md
I just ran into this so I figured it might be helpful for others.
I don't know what other details are really needed, so if something needs to be added, just let me know 👍
> Explain how to fix no output issue

- doc/README-ja.md
- Synchronized the contents of `README.md`.
- Fixed `README.md` to match the line number of text.
- Translated to Japanese.
- Fixed menu link anchor.
Please pardon a sudden pull request.
It is only translation into Japanese as above,
but I'd appreciate if you could merge it if you like 🙏 
Thanks for the wonderful command 🎉
> fix: doc/README-ja.md

- README.md
- doc/README-ja.md
- doc/README-ko.md
Thanks for this amazing project. 
To promote this wonderful tool for Korean engineers, I added Korean translation for README ;)
> add translation into Korean 

- examples/simple.rs
- src/assets.rs
- src/bin/bat/app.rs
- src/bin/bat/assets.rs
- src/bin/bat/config.rs
- src/bin/bat/directories.rs
- src/bin/bat/main.rs
- src/controller.rs
- src/lib.rs
- src/line_range.rs
- src/printer.rs
- tests/no_duplicate_extensions.rs
- tests/syntax_detection.rs
this solves the first point in https://github.com/sharkdp/bat/issues/423#issuecomment-548060410
> Restructure asset handling

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- build.rs
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
> chore: Update liquid to 0.20

- CHANGELOG.md
In an attempt to decrease the amount of work to create new releases (#845), I'm adding a complete CHANGELOG to the repository. The idea is that this will be continuously updated with every PR.
> Add CHANGELOG to the repository

- .gitmodules
- CHANGELOG.md
- assets/syntaxes/02_Extra/Stylus.sublime-syntax
> Add Stylus syntax

- CHANGELOG.md
- assets/patches/Makefile.sublime-syntax.patch
Thanks to @keith-hall!
closes #750
> Add performance patch for Makefile syntax

- build.rs
- src/assets.rs
- src/assets_metadata.rs
- src/bin/bat/app.rs
- src/bin/bat/assets.rs
- src/bin/bat/clap_app.rs
- src/bin/bat/config.rs
- src/bin/bat/main.rs
- src/controller.rs
- src/line_range.rs
- src/preprocessor.rs
- src/printer.rs
- tests/no_duplicate_extensions.rs
Some expressions should be lazy but it didn't are fixed.
> Fix some clippy warnings

- src/bin/bat/main.rs
- src/controller.rs
- src/error.rs
- src/output.rs
> Write error messages to pager, if attached

- Cargo.lock
- Cargo.toml
The tests currently fail on Windows, so I reverted the change on `master`. Opening this PR to track this issue.
see #955
> Use console 0.11.2

- .gitmodules
- CHANGELOG.md
Adds Email syntax (https://github.com/mariozaizar/email.sublime-syntax)
> Adds Email syntax (email.sublime-syntax)

- CHANGELOG.md
- src/controller.rs
- src/printer.rs
- tests/integration_tests.rs
> Add padding above headers when no grid

- src/assets.rs
- src/syntax_mapping.rs
> Fix syntax detection for files called 'rails'

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/assets.rs
> Fix syntax detection for symlinks

- doc/README-ja.md
I modified Japanese document(README-js.md).
I changed three point below.
- translate English sentence into Japanese
- add notes while installing bat through apt command
- fix typo
If you like, please pull my commit.
> modify japanese doc.

- .gitmodules
- CHANGELOG.md
- src/assets.rs
- src/syntax_mapping.rs
- tests/no_duplicate_extensions.rs
> Adds GLSL syntax

- README.md
Addressing https://github.com/sharkdp/bat/issues/1095
> Make Windows 10 dependencies more clear

- README.md
- src/bin/bat/config.rs
As per discussion at #1097, this merge request is a simple modification to give the users more context about the indentation behaviour.
Please review and merge it accordingly! 🙇
> Add clarification about indentation usage

- .github/workflows/CICD.yml
This PR resolves a number of minor packaging issues and brings the debs more into line with Debian packaging guidance for users who install via the .debs published with the Github releases.
> debian packaging fixes

- README.md
addresses [Issue #1154](https://github.com/sharkdp/bat/issues/1154)
> update README to clarify disjunctive licensing

- .gitmodules
- CHANGELOG.md
- assets/README.md
- assets/syntaxes/02_Extra/Apache.sublime-syntax
- src/syntax_mapping.rs
Closes #1107
Hey, I picked this issue to get into `bat`. I added a submodule to the [GitHub repo of the linked syntax highlighting file](https://github.com/brandonwamboldt/sublime-nginx). I tried it out with the example from [the nginx wiki](https://www.nginx.com/resources/wiki/start/topics/examples/full/) and worked as expected.
For Apache, I converted the linked `.tmLanguage` file, but the highlighting is not correct yet (closing tag names are not colored). I am still looking into that, but I wanted to open the pull request early.
That said, thanks for creating `bat`, I use it every day!
> Nginx and Apache config file syntax highlighting

- src/syntax_mapping.rs
@sharkdp this currently what I did & I'm stuck here, not sure why the test
doesn't run.
Closes #1191
> Support XDG_CONFIG_HOME git config files

- .github/workflows/CICD.yml
See https://github.com/sharkdp/bat/pull/1136#issuecomment-695769122
> Fix zsh completion path on packaging

- README.md
> Add new example for --map-syntax

- tests/syntax-tests/highlighted/CpuInfo/test.CpuInfo
- tests/syntax-tests/highlighted/MemInfo/test.MemInfo
- tests/syntax-tests/source/CpuInfo/test.CpuInfo
- tests/syntax-tests/source/MemInfo/test.MemInfo
Adding file for CpuInfo and MemInfo syntax test.
This PR's related to #1213.
> Add syntax tests for CpuInfo and MemInfo filetype

- README.md
Part of https://github.com/sharkdp/bat/issues/448
Thanks to https://github.com/sharkdp/bat/pull/940
> Add git diff example to Integration docs

- README.md
I added / reworded the [automatic paging](https://github.com/sharkdp/bat#automatic-paging) section of the README to include disabling the pager.
> explain how to use bat as cat (no paging) (closes #1383)

- .github/workflows/CICD.yml
> Revert "debian packaging fixes"

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- doc/README-ja.md
- doc/README-ko.md
- doc/README-ru.md
- src/controller.rs
- src/input.rs
- tests/integration_tests.rs
> Revert output-among-inputs change

- CHANGELOG.md
- README.md
Released this package as snap package. adding snap installtion method in readme and added it into chagelog files.
> adding snap installtion command

- CHANGELOG.md
- src/bin/bat/main.rs
> only print themes hint in interactive mode

- .github/workflows/CICD.yml
Refs https://github.com/sharkdp/bat/issues/1352#issuecomment-737054985
This replaces the commits reverted in https://github.com/sharkdp/bat/pull/1393 which are not related to the issue reported in #1352
> Debian package fixes (2)

- .github/ISSUE_TEMPLATE/bug_report.md
Adjusted as requested in #1374 :)
> Simplify comments in bug_report issue template

- Cargo.toml
- README.md
- assets/manual/bat.1.in
- src/bin/bat/clap_app.rs
- Add 'batcat' comment in MANPAGER suggestion, closes #1434
- Improve --map-syntax documentation, closes #1386
- Add comment regarding use of bat as a library, closes #953
> Documentation improvements (WIP)

- .github/workflows/CICD.yml
For increased script modularity.
For convenience I also include the (fixed) commit from https://github.com/sharkdp/bat/pull/1512 in this PR, and will close https://github.com/sharkdp/bat/pull/1512.
For #1474
> Move DPKG_* and PKG_* vars to respective package step

- .github/workflows/CICD.yml
> CICD: Naming (jobs, stages)

- .github/workflows/CICD.yml
> CICD: Build step naming

- LICENSE-MIT
- README.md
- doc/README-ja.md
- doc/README-ko.md
- doc/README-ru.md
> Update copyright year

- .github/workflows/CICD.yml
working example: https://github.com/LukeMathWalker/wiremock-rs/pull/66
> CI: check docs

- doc/README-ko.md
Hi, I updated the Korean version of the README:
- Fix Korean grammar
- Show original English words that can improve comprehensiveness side-by-side
- Reflect the updated README
- Fix broken links
- Other miscellaneous improvements
> Update the Korean version of the README

- doc/README-ja.md
ref: c569774e1a8528fab91225dabdadf53fde3916ea
> Add section about integration with fzf to README-ja.md

- README.md
Given the discussion in #1681, I thought it would be worthwhile to add 'compatibility' as an advantage to our 3-bit theme. I rearrange and reformulated the other points in the list while I were at it.
> README.md: List compatibility as another advantage to 3-bit themes

- tests/.gitattributes
Following the discussion in #1677.
> Linguist repository statistics

- assets/completions/bat.bash.in
https://github.com/sharkdp/bat/pull/1702#issuecomment-872452683
> Add some more options to bash completion

- Cargo.lock
..  to fix an incompatibility with Rust 1.54
See https://github.com/rust-lang/rust/issues/85574
> Update git2 dependency

- assets/manual/bat.1.in
- src/bin/bat/clap_app.rs
> Make --style docs reflect that 'full' is default

- CHANGELOG.md
- assets/patches/Python.sublime-syntax.patch
> add patch for Python syntax to help improve performance

- .github/workflows/CICD.yml
- src/bin/bat/directories.rs
- tests/integration_tests.rs
Example of how a failure looks: https://github.com/Enselic/bat/runs/3360655439?check_suite_focus=true
> CICD: Add 'cargo fmt' check

- src/assets.rs
- src/bin/bat/app.rs
- src/bin/bat/assets.rs
- src/bin/bat/main.rs
- src/controller.rs
- src/input.rs
- src/printer.rs
They are all of the following type:
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
> Fix all lints that are new with Rust 1.54

- .github/workflows/CICD.yml
* Use Ubuntu 20.04 instead of 18.04
* Add statically linked binaries for ARM
(this is a result of a CI sync with `fd` and `hyperfine`)
> Minor CI improvements

- doc/release-checklist.md
Also recommend to just push the tag for the release, and not all tags.
> doc/release-checklist.md: Recommend git push origin tag vX.Y.Z

- src/assets.rs
- tests/syntax-tests/highlighted/Ignored suffixes/test.rs.ucf-dist
- tests/syntax-tests/highlighted/Ignored suffixes/test.rs.ucf-new
- tests/syntax-tests/highlighted/Ignored suffixes/test.rs.ucf-old
- tests/syntax-tests/source/Ignored suffixes/test.rs.ucf-dist
- tests/syntax-tests/source/Ignored suffixes/test.rs.ucf-new
- tests/syntax-tests/source/Ignored suffixes/test.rs.ucf-old
Refs https://manpages.debian.org/bullseye/ucf/ucf.1.en.html
> assets: add Debian ucf backups to ignored suffixes

- src/assets.rs
Reduce code duplication to ease solving #951.
(Expect to see more refactoring PRs soon)
> Add some highlighting assets helpers

- src/printer.rs
The main benefit is that we get rid of a call to `assets.get_syntax_set()`,
which in turn makes it easier to later get rid of `syntaxes.bin`.
> src/printer.rs: Add HighlighterFromSet helper

- README.md
- doc/README-ja.md
- doc/README-ko.md
- doc/README-ru.md
- doc/README-zh.md
I checked the Chinese one and found it out of dated for three years. So I wrote my own version from the original README.md.
> add a README-zh.md as the Chinese version of README.md

- README.md
> README.md: Add 'control characters' to Garbled output section

- assets/manual/bat.1.in
Fixes #1913
Signed-off-by: Mahdi Dibaiee <mdibaiee@pm.me>
> Add note regarding options passed to less by default in manpage 

- CHANGELOG.md
This finalizes the making of the v0.19.0 release (see checklist at https://github.com/sharkdp/bat/pull/2016) :tada:
> CHANGELOG.md: Prepare a new "unreleased" section

- assets/syntaxes/02_Extra/Stylus.sublime-syntax
- doc/README-ko.md
> small typos, should not interrupt anything

- README.md
> README.md: Clarify --map-syntax argument

- CHANGELOG.md
- doc/release-checklist.md
Also put it in the checklist so it is easy to copy-paste next time.
> Prepare a "unreleased" section at the top of `CHANGELOG.md`

- CHANGELOG.md
- Cargo.lock
- src/syntax_mapping.rs
I just mainly added it for myself, you
can choose if merge or not, it's just nice
to see the config file highlighted
Not an important feature, just nice I guess lol
Just close this PR if you decide not to merge :)
> Syntax: add clang-format

- CHANGELOG.md
This is in preparation of the v0.21.0 release so that the diff becomes smaller when it is time to make the release for real.
> CHANGELOG.md: Clean up and tweak

- .github/dependabot.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Add github-actions to Dependabot

- doc/assets.md
The only change of "substance" here is the tweak for the Apache file types, others are cosmetic things noticed while working on #2356.
> Fix up punctuation and sorting in manual modifications doc

- assets/syntaxes/02_Extra/INI.sublime-syntax
- doc/assets.md
<https://coverage.readthedocs.io/en/6.3.2/>
> Add new file_extensions for INI

- .github/workflows/CICD.yml
- Extract metadata using `cargo metadata` and `jq`, instead of grepping
- Use macos-12 image
> CI improvements

- Cargo.lock
- Cargo.toml
Update `serial_test` to 2.0 and `predicate` to 3.0.
> Update dev dependencies 

- src/syntax_mapping/ignored_suffixes.rs
Refs https://www.debian.org/doc/manuals/debian-handbook/sect.package-meta-information.en.html#sect.conffiles
> Add .dpkg-new and .dpkg-tmp to ignored suffixes

- src/printer.rs
`printer.rs` defines `write_handle` and `writeln_handle` for `OutputHandle` but actually we can reuse standard `write` and `writeln` macros by defining `write_fmt` method for the struct. Starndard macros are better in terms of readability since they are well-known. In contrast defining our own macros means that readers need to know how they are expanded.
> Replace our own macros to write buffers with standard macros

- CHANGELOG.md
I can never remember to write changelog. Maybe I can add a CI check for this.
> Write changelog for #2756

- .github/workflows/require-changelog-for-PRs.yml
- CHANGELOG.md
> Use GitHub API to get correct PR submitter

- doc/README-ru.md
Fixed syntax typo in Russian ReadMe.md
https://github.com/sharkdp/bat/issues/2777
> fixed syntax typo in russian readme

- CHANGELOG.md
- src/controller.rs
> Make `Controller::run_with_error_handler`'s error handler `FnMut`

- CHANGELOG.md
- src/printer.rs
- tests/examples/this-file-path-is-really-long-and-would-have-broken-the-layout-of-the-header.txt
- tests/integration_tests.rs
My humble attempt at closing #2817
> fix: Wrap file name in header

- CHANGELOG.md
- src/vscreen.rs
- tests/tester/mod.rs
Fixed all `cargo clippy` complaints.
> Apply clippy fixes

- CHANGELOG.md
- src/syntax_mapping/builtins/common/xonsh.toml
Hey! Thank you for `bat` it's awesome!
Add [xonsh shell](https://xon.sh) support.
Thanks!
> Added xonsh shell support

- CHANGELOG.md
- src/syntax_mapping/builtins/linux/50-containers.toml
See https://github.com/containers/image/tree/main/docs.
> Map containers `.conf` files to TOML syntax

- CHANGELOG.md
- assets/patches/JavaScript.sublime-syntax.patch
Implemented as a patch for now.
Already contributed upstream: https://github.com/sublimehq/Packages/pull/3942
> [JavaScript] Support bun in shebang for syntax highlighting

- .github/workflows/CICD.yml
- CHANGELOG.md
Add build job for Apple Silicon to address #2962
> Add support for Apple Silicon

- assets/completions/bat.zsh.in
Remove the duplicate word `disable disable`
> bat.zsh.in: Remove duplicate word

- CHANGELOG.md
> Use TOML syntax highlighting for uv.lock

- assets/syntaxes/02_Extra/Manpage.sublime-syntax
- assets/syntaxes/02_Extra/syntax_test_man.man
> Manpage: Fix for OPTIONS consisting of a plain dash

- CHANGELOG.md
Add new unreleased section at top of change log
> Post release steps

- CHANGELOG.md
- assets/syntaxes/02_Extra/apt-source-list.sublime-syntax
- tests/syntax-tests/highlighted/debsources/sources.list
- tests/syntax-tests/source/debsources/sources.list
> Add debsources syntax

- CHANGELOG.md
- src/assets.rs
- tests/integration_tests.rs
> Make map-syntax target case insensitive

- README.md
- doc/README-zh.md
https://github.com/sharkdp/bat/pull/3362#issuecomment-3166706199
- Use `awk`instead of `sed` for portability;
- Update Chinese docs.
> Make MANPAGER more portable

- CONTRIBUTING.md
To reduce load on maintainers.
> CONTRIBUTING.md: Note that new themes are not desired right now
