sharkdp/bat

.travis.yml, src/main.rs
Closes #29 
The huge diff (just whitespace) is because I needed to introduce a new scope because `wait()` borrows mutably
=> Add less pager

src/main.rs, src/terminal.rs
Closes  #26 
Colors are disabled if the terminal is not interactive unless explicitly
set otherwise
=> Add color flag

src/main.rs
Another point to fully address #26.
=> Use 'plain' style for non-interactive terminals

src/main.rs, src/printer.rs
This adds a separate struct that handles printing of the different
tokens.
I think this makes it easier to control the style without making the code too noisy. Just a simple guard check at the top of the relevant function before early exiting. I got it to the same state as master now, but the new proposed style features in #74 would be easier to understand. One caveat of this style is more allocations. Sorry about the huge code dump. Since we didn't discuss this beforehand, it's fine to close if you want to follow a different path.
/cc: @sharkdp @pitkley
=> Add printer

README.md, src/main.rs
* Remove the old `init-cache` subcommand
* Introduce a new `cache` subcommand that can be used like this:
* `bat cache -h` - Show help
* `bat cache --init` - Initialize cache from config dir
* `bat cache --clear` - Reset the cache
* `bat cache --config-dir` - Show config directory
* Update README
closes #44
=> Improve cache subcommand

src/main.rs, src/printer.rs
Closes #69 
```
$ ./target/debug/bat.exe Cargo.toml --list-languages
ASP                              | asa
HTML (ASP)                       | asp
ActionScript                     | as
AppleScript                      | applescript, script editor
Batch File                       | bat, cmd
NAnt Build File                  | build
C#                               | cs, csx
C++                              | cpp, cc, cp, cxx, c++, C, h, hh, hpp, hxx, h++, inl, ipp
C                                | c, h
--snipped--
```
=> Add "--list-languages" command line argument

src/app.rs
=> Enable ANSI support on Windows 10

src/main.rs
=> sort the language listing

src/app.rs, src/decorations.rs, src/diff.rs, src/main.rs, src/printer.rs, src/style.rs, src/terminal.rs, tests/snapshots/output/changes,grid,header.snapshot.txt, tests/snapshots/output/changes,grid.snapshot.txt, tests/snapshots/output/grid,header,numbers.snapshot.txt, tests/snapshots/output/grid,header.snapshot.txt, tests/snapshots/output/grid,numbers.snapshot.txt, tests/snapshots/output/grid.snapshot.txt, tests/tester.rs
I use bat pretty frequently, so I wanted to give back and make it even better by adding text wrapping (issue #54).
I've never touched Rust before this, and I apologize if the code style is weird or if any of my changes have less-than-ideal performance.
- **Text wrapping.**
Lines will now automatically wrap at a character boundary.
Syntax coloring will also wrap.
- **Resizing gutter (panel).**
The gutter (area that shows line numbers and changes) will now automatically resize.
This cuts back on the amount of wasted space when not showing everything.
It will also disappear if not needed.
=> Added text wrapping. (Fixes #54)

src/assets.rs, src/main.rs
I was initially going for the last performance improvement in #20, but there were many lifetime issues caused by introducing the threads. Maybe someone else can tackle that
=> Extract syntax finding to assets module

src/printer.rs
Fixed #124 by using `console::AnsiCodeIterator`. 
Due to the way that all the input is formatted with the default styling before being printed, I had to use the ANSI escape sequences as prefixes to the input text. Not doing so would result in the ANSI styles being overridden like so: `\x1B[32m\x1B[0m`. It's not an elegant solution, and it definitely doesn't help performance, but it works.
=> Fixed #124

src/output.rs
Fix launching of pager so all control characters are interpreted
instead of only ANSI "color" escape sequences.
This fixes issue https://github.com/sharkdp/bat/issues/98
=> Fix launching of pager so all control characters are interpreted.

src/app.rs
See https://docs.rs/clap/2.31.2/clap/enum.AppSettings.html#variant.AllArgsOverrideSelf
This is useful if people use something like this in their `.bashrc` files:
``` bash
alias bat="bat --theme=TwoDark --paging=never"
```
because it allows them to override some of these defaults later:
``` bash
> bat --theme=1337
```
=> Allow arguments to override themselves

src/features.rs
That would fix the type annotation error discussed in #148
=> Using slice notation instead of as_ref

Cargo.lock, Cargo.toml, tests/tester.rs
=> Use separate Git repository for snapshot testing

src/app.rs, src/features.rs, src/main.rs, src/printer.rs
This is my first attempt at actually writing some rust code so bear with me.
I wasn't sure of the best place to put the logic for checking line range. I started with putting it in the print_line function but moved it out to be able to short circuit and stop processing once out of the range.
I didn't add the ability to do multiple ranges yet but it should be fairly simple.
How robust of error checking do we need on validating the line ranges? Like do we want to sort or make sure they are not conflicting or that they are in least to greatest order or anything like that?
=> add line-range

src/app.rs, src/assets.rs, src/features.rs
The `--theme` command line option stills takes precedence and this
change preserves how errors are handled when it's used: If a theme name
that doesn't exist is specified using the argument, this error is fatal.
However, if a theme that doesn't exist is specified using the environment
variable, the error is logged to `stderr` and the "Default" theme is
loaded as a fallback.
This a refactor/variation of sharkdp/bat#187 based on feedback from @sharkdp.
Fixes sharkdp/bat#177
=> Allow specifying the theme via the `BAT_THEME` environment variable

src/app.rs, src/features.rs, src/printer.rs
Instead of using `Box` we can use generic for `print_file_ranges`. It is just a matter of taste, I don't know which one is better.
=> replace trait object BufRead by generic

README.md, src/assets.rs
This commit separates the handling of syntax sets and theme sets. It
also changes the way how new syntax definitions are loaded from `bat`'s
configuration folder. New syntax definitions are now loaded *in
addition* to the ones that are stored in the `bat` binary by default.
This fixes #172
=> Separate syntax set and theme set

src/app.rs
- Call `enable_ansi_support` only once.
- Ignore errors that appear when trying to enable ANSI support. This
will hopefully fix #252 and fix #264
=> Ignore enable_ansi_support errors

src/output.rs
The current logic for special-casing `less` relies on the pager being specified as the literal string or using Unix-style paths. It also ignores the actual pager specified when calling it, so even if you set `PAGER`/`BAT_PAGER` to `/my/path/to/less`, `bat` will simply call `less`.
This PR treats any specified pager as a path and checks only the file stem so that `C:\foo\bar\less.exe`, `/foo/bar/less`, and `less` are all recognized.  It also uses the specified `less`.
I managed to write a test for this by creating a stub `bin/less.rs` that verifies its arguments and the environment. However, this binary was installed along with `bat` when running `cargo install`. [I haven’t yet found a way to test the behaviour without this issue](https://stackoverflow.com/q/52205295/8492116), so for the …
=> Handle `less` in a portable way

src/app.rs, src/style.rs
This is a fix for #289. As I explained in my reply [here](https://github.com/sharkdp/bat/issues/289#issuecomment-419501495), it didn't make sense to leave wrapping on with `--plain`, since the terminal is more than capable of wrapping the lines itself when the sidebar isn't used.
=> Disable wrapping when --plain is used. (Fixes #289)

src/printer.rs
In large git repo like chromium, it takes too long time to query git diff.
=> Query git diff only when needed

README.md
On Ubuntu 18.04 I had to install `cmake` as well as `libz-dev` to get bat to compile.
=> Update README (libz-dev may be required)

README.md
Since #263 was closed, I thought it would be a good idea to add the wrapper function to the README with an explanation so we don't end up with duplicate issues about `/cygdrive` paths.
=> Added section to README on using Cygwin.

Cargo.lock, Cargo.toml, src/app.rs, src/main.rs
Windows does not support wildcard expansion in cmd,
this adds 'wild' crate (as discussed in #309) that handles everything transparently,
so wildcards work everywhere.
Fixes #309
=> Add support for wildcards in Windows CMD

Cargo.lock, Cargo.toml, src/inputfile.rs, src/main.rs, src/printer.rs
```
▶ bat text_UTF-16LE-BOM.txt
───────┬─────────────────────────────────────────────────────────────────
│ File: text_UTF-16LE-BOM.txt   <UTF-16LE>
───────┼─────────────────────────────────────────────────────────────────
1   │ ﻿simple text and
2   │ some characters like 🌂, 💖, ä, 𝄞, € and ∰
───────┴─────────────────────────────────────────────────────────────────
▶ bat text_UTF-16BE-BOM.txt
───────┬─────────────────────────────────────────────────────────────────
│ File: text_UTF-16BE-BOM.txt   <UTF-16BE>
───────┼─────────────────────────────────────────────────────────────────
1   │ ﻿simple text and
2   │ some characters like 🌂, 💖, ä, 𝄞, € and ∰
───────┴─────────────────────────────────────────────────────────────────
```
closes #285
=> Add support for UTF-16LE and UTF-16BE

README.md
`bat` is available in through the nix package manager. Added that install option to the README.
=> Documented nix availability

README.md
Should fix #328 - describes steps for using a theme compatible with light terminal backgrounds.
=> Fixes #328 - adds info for light backgrounds.

src/controller.rs, src/output.rs, tests/integration_tests.rs
I'm a bit unsure of Rust error handling. Probably also missing a test, but lets just ack the code change first maybe.
Solves #352
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> Add arguments from PAGER/BAT_PAGER

src/app.rs, src/assets.rs, src/clap_app.rs, src/main.rs, src/printer.rs, src/syntax_mapping.rs
This adds a `-m`/`--map-syntax` option that allows users to (re)map
certain file extensions or file names to an existing syntax.
For example:
```
bat --map-syntax .config:json ...
```
The option can be use multiple times. Note that you can easily make
these mappings permanent by using `bat`s new configuration file.
closes #169
=> Implement syntax mapping

src/app.rs, src/clap_app.rs
=> When specifying style multiple times the last occurence wins

src/app.rs, src/clap_app.rs
Allows the `width` argument to `--terminal-width` to be an offset
instead of an absolute number. Examples:
--terminal-width=80   # Set output width to 80 characters
--terminal-width=-2   # Set output width to actual_width - 2
closes #376
=> Allow offset values in `--terminal-width`

assets/syntaxes/show-nonprintable.sublime-syntax, src/app.rs, src/clap_app.rs, src/controller.rs, src/preprocessor.rs, src/printer.rs
Adds a new `-A`/`--show-all` option (in analogy to GNU Linux `cat`s option) that
highlights non-printable characters like space, tab or newline.
This works in two steps:
- **Preprocessing**: replace space by `•`, replace tab by `├──┤`, replace
newline by `␤`, etc.
- **Highlighting**: Use a newly written Sublime syntax to highlight
these special symbols.
Remarks:
- This feature is not technically a drop-in replacement for GNU `cat`s `--show-all` but it has the same purpose.
- This replaces normal syntax highlighting. You can not use syntax highlighting with `--show-all`.
- Tab-width can be controlled via `--tabs N`
- This closes #381 (see also: #228)
=> Feature: Highlight non-printable characters

src/config.rs, tests/examples/bat.conf, tests/integration_tests.rs
Work in progress PR for #375 
Happy to change as you see fit, tested manually with a --style=numbers line, looking for a good way to write an integration test for the config `$VAR`
=> [WIP] Enviroment var config

README.md
I maintain the package for `bat` on openSUSE.
=> Add openSUSE installation instructions

src/output.rs
This PR fix issue #383.
I had to make `pager` a mutable variable, please let me know if there's a better way.
=> Avoid endless bat executions with PAGER="bat"

assets/README.md, assets/syntaxes/INI.sublime-syntax
Reference: https://standards.freedesktop.org/desktop-entry-spec/latest/
=> Highlight XDG desktop entry as .ini file

src/app.rs, src/syntax_mapping.rs
Just a tiny PR which uses impl Trait so that one does not have to specify `into` in the arguments :smile:
=> Enhance SyntaxMapping with impl Trait

README.md
Solves #419 by removing confusing the variable `BAT_CONFIG_DIR` from examples because it is not a real configuration option for bat.
=> Removed confusing variable from examples in README.md

src/app.rs, src/clap_app.rs, src/printer.rs, src/terminal.rs
Continuing the work of #346 (/CC @tskinn)
* Allow for multiple occurrences of `--highlight-line <N>`
* Highlight the full line
* Proper handling for overlong lines
closes #175
=> Line highlight

src/controller.rs, src/inputfile.rs, src/main.rs
=> Exit on first EOF from stdin

src/output.rs
=> Do not parse arguments in PAGER

README.md, assets/README.md, assets/create.sh, doc/README-ja.md, src/clap_app.rs, src/main.rs
* Rename `bat cache --init` to `bat cache --build`
* Move `--config-dir` and `--cache-dir` from 'bat cache' to 'bat' and hide them from the help text.
@lavifb FYI
=> Refactor cache subcommand

tests/integration_tests.rs
Relates to discussion on PR #492.
=> Add integration tests running bat with empty input files.

src/controller.rs, src/inputfile.rs, src/main.rs
This avoids waiting for a second EOF from stdin, and preserves header and footer for empty stdin and files. This is an alternative to #492 (reverted) as a solution to #477.
=> Only print contents of file if not empty.

assets/syntaxes/FSharp.sublime-syntax
This new syntax file is based on [Ionide's grammar file @ be0bdfd1](https://github.com/ionide/ionide-fsgrammar/blob/be0bdfd1/grammar/fsharp.json), which also fixes some problems with the previous one.
=> Update F# syntax

doc/bat.1
The `--highlight-line` option is missing from the manual. 
Issue: https://github.com/sharkdp/bat/issues/546
I have not checked if more options are missing but this is still a improvement over previous manual.
=> Updated manual to include -H, --highlight-line <N>

src/app.rs, src/clap_app.rs
A potential solution to #552 without breaking backwards compatibility or `cat` compatibility.
This introduces the `-pp` option, which does the following:
1. `--style=plain` (carried over from `-p`)
2. `--paging=never`
=> Add `-pp` for plain styling and no pager

src/clap_app.rs
My proposed solution to #535, which involves validating `--terminal-width` to report an error if somebody provides a width of zero.
User convenience is definitely something to consider, but in this instance I believe having `--terminal-width=0` being analogous to `--wrap=never` would be more of a quirky behaviour than a quality-of-life feature.
1. Having such a feature would dilute the meaning of `--terminal-width`.
2. Using `--terminal-width=0` as `--wrap=never` isn't very clear or intuitive.
3. Using `--terminal-width=0` as a way to disable wrapping results in a conflict when you don't want wrapping, but do want to specify a specific terminal width.
4. It's more explicit (and less characters) to type `--wrap=never`.
=> Prevent `--terminal-width=0` and invalid forms of `--terminal-width`.

src/printer.rs
Fixes #551.
It turns out that I made a couple mistakes when initially implementing escape passthrough. This improved implementation is still making a few assumptions about the escape sequences (CSI/SGR sequences are safe to concatenate and use as a prefix, and all others are safe to pass through), but it should be a bit more reliable when fed any other sequences.
=> Improved logic when encountering ANSI/VT100 in character wrap mode

assets/completions/bat.fish, src/main.rs
This a pull request to solve the TODO at line 19 in the fish shell completions.
https://github.com/sharkdp/bat/blob/e7c5561df736d42734c39712c52abc19ec9aa8d5/assets/completions/bat.fish#L19-L20
The basic principle of the solution is the same as what I described in #553, and it has the same caveats, but this is a better implementation that only uses `awk`.
- Lists all languages from `bat --list-languages`.
- Displays the full name of the language.
- Filters out languages that are probably config files (starts with an upper case letter).
In order to properly parse the output of `bat --list-languages`, two conditions need to be met with the first language that appears in the list.
1. There is at least two spaces after the language name (i.e. is not the longest name).
2. The language name does …
=> Add completions for `--language` when using the fish shell.

src/inputfile.rs, src/printer.rs
Instead of printing
```
───────┬─────────────────────────────────────────────────────────
│ File: some-file
───────┼─────────────────────────────────────────────────────────
───────┴─────────────────────────────────────────────────────────
```
for empty files, bat will now print
```
───────┬─────────────────────────────────────────────────────────
│ File: some-file   <EMPTY>
───────┴─────────────────────────────────────────────────────────
```
closes #563
=> Only print the header for empty files

.gitmodules, assets/README.md, assets/syntaxes/Org mode.sublime-syntax
=> Add Org mode syntax

src/assets.rs
Fixes #576
I'm assuming no tests are needed, since I've found none re this.
=> Enforce the creation of the full cache dir path

.gitmodules, assets/syntaxes/Hosts.sublime-syntax
- Syntax author: https://github.com/brandonwamboldt/sublime-hosts
Since the upstream version only has a tmLanguage, added a sublime-syntax
file manually.
=> Add support for "etc/hosts" files.

.gitmodules
Tested:
```
bash assets/create.sh
cargo build
target/debug/bat --language ssh_config ~/.ssh/config
```
=> Add SSH config syntax

README.md
Anything older than F29 is EOL now, so no need to mention it. Also in F29+ you can use standard `dnf install`.
=> Small improvements for Fedora instructions

src/controller.rs, src/output.rs, src/printer.rs
trait objects without an explicit dyn have been deprecated in 1.37
=> use explicit dyn with Write to appease compiler

.gitmodules
Thanks for bat! This appeared to be the GraphQL sublime syntax project with the most traction and in my limited testing so far I have not seen any problems:
=> Add GraphQL sublime syntax submodule

.travis.yml, ci/before_install.bash
This PR is a reminder to re-enable aarch64 builds. There is currently a problem with the cross-compilation of `onig_sys`.
=> Re-enable aarch64 builds

src/clap_app.rs, src/controller.rs, src/printer.rs, src/style.rs, tests/integration_tests.rs
My solution to my own issue, #569.
When specifying multiple line ranges with `--line-range=... --line-range=...`, the printed lines tend to blend together and make it difficult to determine the scope of each range.
Example which makes parts of three functions look as though they're a single function:
The "snip" separator is implemented as another style component much like header and grid. I chose to include it in the `full` style by default, since doing otherwise would no longer make it "full".
When not using the `full` style, it can be added as `snip`.
=> Add new style component to separate multiple '--line-range's

assets/syntaxes/show-nonprintable.sublime-syntax, src/clap_app.rs, src/preprocessor.rs, src/printer.rs
Closes #623. When the `-A` flag is supplied, attempts to print hex-escaped lines for binary files. The one caveat is it escapes non-ASCII characters, not just non-UTF-8.
From what I could tell printing the hex-escaped version of UTF-8 text would be a lot more involved, but if there's an option I missed here I'm happy to make changes
=> Display binary file content for bat -A

README.md
This PR adds a section to readme explaining how to configure `bat` to use different theme for the macOS dark mode feature
=> add dark mode script

README.md
Fixes #655.
Rather than referring to `bat-extras` directly, I added the supported integrations to the relevant section in the README.
=> Add references to scripts in `bat-extras`

.gitmodules
Adding new syntax highlighting for SaltStack states - SLS files.
Example:
=> Add SaltStack SLS syntax

assets/syntaxes/Group.sublime-syntax, assets/syntaxes/Passwd.sublime-syntax
These syntax files do not follow any good [scope naming](https://www.sublimetext.com/docs/3/scope_naming.html). I have just tried to make everything look distinct.
=> Add syntax highlighting for /etc/group and /etc/passwd

assets/syntaxes/Resolv.sublime-syntax
Added simple keyword highlighting for /etc/resolv.conf
=> Add syntax highlighting for /etc/resolv.conf

assets/syntaxes/Fstab.sublime-syntax
This commit adds simple syntax definitions for `fstab` files.
=> Add fstab syntax definitions

README.md
Documentation update to fix #323
To install:
```
Reading package lists...
Building dependency tree...
Reading state information...
bat is already the newest version (0.11.0-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
───────┬────────────────────────────────────────────────────
│ File: /etc/os-release
───────┼────────────────────────────────────────────────────
1   │ NAME="Ubuntu"
2   │ VERSION="19.10 (Eoan Ermine)"
3   │ ID=ubuntu
4   │ ID_LIKE=debian
5   │ PRETTY_NAME="Ubuntu 19.10"
6   │ VERSION_ID="19.10"
7   │ HOME_URL="https://www.ubuntu.com/"
8   │ SUPPORT_URL="https://help.ubuntu.com/"
9   │ BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
10   │ PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/te
│ rms-and-policies/privacy-policy"
11   │ …
```
=> doc: Add Ubuntu/Debian bat package to Readme

assets/manual/bat.1.in, src/bin/bat/clap_app.rs
As discussed in #653, this commit updates the sort order of --help options in order to improve usability/importance putting most useful/used commands on top. 
In addition to that, similar options were grouped (or kept) together.
=> Update options sort order in --help and manpage file

src/terminal.rs
This fixes bug #601. Simply prevents empty strings passed to `as_terminal_escaped` from being escaped.
=> Leave blank lines blank for terminal output.

README.md, doc/README-ja.md
Hi.
`Japanese` is `日本語` in Japanese. And, `日本文` is `Japanese` in Chinese. This commit fix this wrong expression.
=> Fix '日本文' to '日本語'

README.md, src/less.rs, src/lib.rs, src/output.rs
With this change, we do not pass the `--no-init` option in newer
versions of less (530 or higher).
This fixes #749
=> Do not pass '--no-init' on newer less versions

src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/lib.rs, src/line_range.rs, src/printer.rs
`--highlight-line` now accepts line ranges like the `--line-range` option.
=> Adds range syntax for line highlights

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/syntax_request.md, diagnostics/info.sh
The shell script is intended to be used to help maintainers and contributors diagnose issues that other people are having with `bat` and/or integration with external tools.
It asks for consent to collect data, and will print the following if everything is allowed:
```
========== system ==========
+ uname -srm
Darwin 18.7.0 x86_64
+ sw_vers # or lab_release on Linux
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
========== bat ==========
+ bat --version
bat 0.12.1
+ env
BAT_PAGER=
PAGER=/usr/local/bin/less
========== bat_config ==========
+ cat /Users/eth-p/.config/bat/config
--tabs 4
#--map-syntax From:to
========== bat_wrapper ==========
+ cat /Users/eth-p/.local/bin/bat
#!/usr/bin/env bash
ARGS=()
case "$(defaults read -globalDomain AppleInterfaceStyle 2>/dev/null || …
```
=> Add issue templates and a `info.sh` tool for helping collect and report system info.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/syntax_request.md
Just a few small things that I thought about after looking how the new templates look like on GitHub.
The main change is that I made the "header" section into a HTML comment. This way, users will not have to remove the header part.
@eth-p What do you think?
=> Simplify issue templates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
This fixes the `diagnostics/info.sh` link in the Bug Report template, and changes the other template names/descriptions to be more consistent in casing and punctuation.
=> Fix broken link in issue template.

src/terminal.rs
Old version of the code did not allowed for `bold italic` or `bold underline` styles
=> Support combination of multiple styles at the same time

Cargo.lock, tests/syntax_detection.rs
This adds some basic tests for our syntax detection. In the future, this should be expanded to contain a comprehensive list of cases that we want to cover.
Once #592 is implemented, we can also add path => syntax mappings within these tests.
=> Add syntax detection unit tests

src/dirs.rs
- if set, BAT_CACHE_DIR is used. otherwise use OS default.
Closes #829
=> Specify cache dir with BAT_CACHE_DIR

Cargo.lock, Cargo.toml, README.md, assets/manual/bat.1.in, doc/README-ja.md, doc/README-ko.md, src/assets.rs, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/errors.rs, src/syntax_mapping.rs
This PR changes the way `--map-syntax` works. The option now works like this:
```
--map-syntax <glob-pattern>:<syntax-name>
```
(this is a breaking change, users will have to adapt their config files)
This PR also adds a builtin database of syntax mappings to `bat` to handle cases such as:
* Glob-based lookups for paths:
* `/proc/cpuinfo` => `CpuInfo syntax`
* `**/.ssh/config` => `SSHConfig`
* `/etc/profile` => `Bash`
* `*.h` => `C++` (I assume this is a better default than "Objective C")
* Files named `build` are no longer mapped to "NAnt Build File" (which should only match `*.build` files). Instead, we use the first-line detection mechanism on such files.
closes #592, closes #685  
see also:  #501
=> glob-based syntax mapping

README.md, src/bin/bat/clap_app.rs, src/bin/bat/config.rs, src/bin/bat/main.rs
I took a shot at implementing the `--generate-config-file` feature request per #870.
This is my 1st foray into Rust so I'm open to feedback/suggestions for improvement.  Also... thoughts on if the default config file content is sufficient or should be modified?
Thanks!
=> Add option to generate a default config file, fixes #870

assets/README.md, assets/syntaxes/Rego.sublime-syntax
This adds support for Rego, the declarative policy language for Open Policy Agent,
https://github.com/open-policy-agent/opa
Generated from:
https://github.com/open-policy-agent/opa/blob/master/misc/syntax/textmate/Rego.tmLanguage
Using:
https://github.com/aziz/SublimeSyntaxConvertor
Example:
=> Add OPA Rego syntax

Cargo.toml
Fixes #896. The "3.2.0" requirement means the same thing as \>=3.2.0 \<4.0.0. This way:
- the bat application will continue using 3.3.0 as per the lockfile;
- bat-as-a-library will pull in the most recent semver compatible version in that range just like before;
- downstream code is free to pin older versions as needed.
=> Allow using bat-as-a-library with older syntect

Cargo.toml, build.rs, ci/script.bash, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/bin/bat/config.rs, src/bin/bat/directories.rs, src/bin/bat/main.rs, src/config.rs, src/controller.rs, src/decorations.rs, src/diff.rs, src/errors.rs, src/less.rs, src/lib.rs, src/output.rs, src/printer.rs, src/style.rs, src/terminal.rs, tests/tester.rs
Fixes #895. This PR introduces a `features = ["application"]` which is enabled by default and pulls in everything required by bat the application. When depending on bat as a library, downstream Cargo.toml should disable this feature to cut out inapplicable heavy dependencies like liquid.
```toml
[dependencies]
bat = { version = "0.13", default-features = false }
```
I've put some other optional functionality behind features as well: paging and git support, neither of which I would want for cargo-expand.
=> Strip dependencies of bat-as-a-library

Cargo.lock, Cargo.toml, ci/script.bash
This PR updates the `syntect` dependency to 4.1.
It also adds a `regex-onig` feature (enabled for the application) and a `regex-fancy` feature, which can be enabled to use `fancy-regex` as an engine in `syntect`.
With this change, applications which depend on `bat` as a library, can use
``` toml
[dependencies.bat]
version = "…"
default-features = false
features = ["regex-fancy"]
```
to remove the `onig` dependency. The full dependency tree after this update is attached below.
One problem that has not yet been resolved is the included set of syntaxes, which is *not* fully compatible with `regex-fancy` (due to regex rewriting, as described in the [syntect 4.0 release notes](https://github.com/trishume/syntect/releases/tag/v4.0.0)) because it has been built with a version of `bat` that uses …
=> Update to syntect 4.1, fancy-regex support

tests/scripts/find-slow-to-highlight-files.py
This PR adds a script that goes through all languages that are supported by 'bat'. For each language, it loops over the correspoinding file extensions and searches a given folder for matching files. It calls 'bat' for each of these files and measures the highlighting speed (number of characters per second). The script reports files which lead to slow highlighting speeds or errors during the execution of 'bat'.
Here are some results:
- I found a couple of C# `*.cs` files. This was expected and will be fixed in the next release (see #677)
- I found a couple of `*.gemspec` and `*.rake` files (Ruby) which lead to a panic. This is a minified example:
```ruby
<<END_DESC
Test
END_DESC
```
Apparently, there is a problem with heredocs in the Ruby syntax: …
=> Add script to find slow-to-highlight files

README.md
A cursory reading of the existing text would lead a reader to think `bat`should be available on Debian, which isn't really true. Most users are not running Sid, so `bat` isn't yet available to them.
=> Clarify the Ubuntu/Debian install instructions

Cargo.lock, diagnostics/info.sh
This should help in diagnosing issues when people have `cat` aliased to `bat`.
=> Add cat alias detection to info.sh

examples/cat.rs, examples/simple.rs, src/assets.rs, src/bin/bat/app.rs, src/bin/bat/main.rs, src/config.rs, src/controller.rs, src/inputfile.rs, src/printer.rs
=> Use --file-name to detect syntax highlighting

CHANGELOG.md, src/output.rs
When using `less` version 551 or newer, `bat` will now pass the `--mouse` argument, allowing
for (better) mouse scrolling support in some terminals.
closes #904
=> Pass '--mouse' to less versions >= 551

.gitignore, CHANGELOG.md, Cargo.lock, Cargo.toml, src/assets.rs, src/assets_metadata.rs, src/bin/bat/assets.rs, src/bin/bat/directories.rs, src/bin/bat/main.rs, src/errors.rs, src/lib.rs
When saving/reading user-provided syntaxes or themes, `bat` will now maintain a
`metadata.yaml` file which includes information about the `bat` version which was
used to create the cached files. When loading cached files, we now print an error
if they have been created with an incompatible version
closes #882
=> Add metadata information to cached assets

README.md
The readme phrasing is incorrect in regard of the dark mode detection on macOs, this PR fixes that.
=> Fix README phrasing about dark mode

.travis.yml, CHANGELOG.md, README.md, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/controller.rs, src/pretty_printer.rs, src/printer.rs
This PR adds a new `--diff` option that can be used to only show lines close to Git changes, i.e. added, removed or modified lines.
The amount of additional context can be controlled with `--diff-context=N`.
Using this like
``` bash
batdiff() {
git diff --name-only --diff-filter=d | xargs bat --diff
}
```
essentially results in a version of `git diff` with syntax highlighting (but without being able to see the old version).
closes #23
=> bat --diff

diagnostics/info.sh
This pull request changes `info.sh` to detect and use `batcat` if `bat` is unavailable, and also adds a warning if `bat` was not found and `batcat` was. This should help with diagnosing any current and future issues when `bat` was installed through the Debian repository.
=> Add 'batcat' detection and notice to 'info.sh'

assets/themes/base16.tmTheme, src/terminal.rs
This changes the base16 theme back from #RRGGBB**0f** to #RRGGBB**00**,
reverting part of #934. That PR used the 0f encoding to produce ANSI
escape sequences 30-37 and 40-47 rather than 38;5 and 48;5 which require
256-color support. Unfortunately, it resulted in base16 using the wrong
colors because ansi_term does not support the bright variants (90-97 and
100-107) so it simply mapped them to the non-bright colors.
This PR makes combines the 00 and 0f alpha encodings into 00, and makes
them use the Color enum for the first 8 colors and Fixed otherwise. This
means the ansi-light and ansi-dark themes will work on terminals without
256-color support, and base16 will render bright colors correctly.
Note: I have not updated themes.bin.
=> Fix base16, and combine 00 and 0f alpha encodings

CHANGELOG.md, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/pretty_printer.rs, src/printer.rs, src/style.rs
This pull request changes two things:
1. *(bat-as-a-library; breaking change)*
When the `git` feature is not enabled, it removes `PrettyPrinter::vcs_modification_markers`. This function was previously being exposed when the feature was disabled, despite not having any effect when used.
2. *(bat)*
Adds `cfg` flags to allow the `bat` application to build without requiring the `git` feature. This would allow people to build `bat` without git support if they don't feel they would need or use it.
Caveats: Unfortunately, disabling the feature doesn't change the help text or generated manpage.
=> Allow 'bat' application to built without git feature, remove PrettyPrint git support when feature not enabled.

CHANGELOG.md, src/assets.rs, src/controller.rs, src/error.rs, src/printer.rs
That's one less TODO :)
I split it into two different `ErrorKind`s, in case we ever want to differentiate between a user providing an invalid syntax name, or `bat` not being able to determine the correct syntax.
=> Refactor HighlightingAssets::get_syntax to return Result type

CHANGELOG.md, src/pretty_printer.rs
I'd like to release a new version of `bat` without breaking changes in the library. @eth-p what do you think?
We could still remove it later when introducing other breaking changes as well.
=> Make 'vcs_modification_markers' change non-breaking

CHANGELOG.md, src/bin/bat/app.rs, src/bin/bat/clap_app.rs
Adds support for the `NO_COLOR` environment variable.
When `NO_COLOR` is provided:
- The help text is not colored.
- Colors are disabled when using `--color=auto`. Note: `--color=always` overrides the environment variable.
=> Add support for NO_COLOR env var (#1021)

.gitmodules, assets/syntaxes/02_Extra/AsciiDoc.sublime-syntax
I've updated the AsciiDoc syntax to a newer version (from the AsciiDoctor project) which happens to work with fancy-regex. My problem originally was that [nushell](https://github.com/nushell/nushell) was crashing when I tried to open adoc files. I found that they get their syntax from here.
I wholeheartedly agree with the discussion in this issue BTW: https://github.com/sharkdp/bat/issues/919, consolidation might make things easier.
=> Updated AsciiDoc syntax submodule

CHANGELOG.md, examples/inputs.rs, examples/yaml.rs, src/assets.rs, src/bin/bat/app.rs, src/bin/bat/input.rs, src/bin/bat/main.rs, src/input.rs, src/lib.rs, src/pretty_printer.rs, src/printer.rs
This pull request refactors the `InputDescription` struct into something consumable in a public API, and removes all special handling for the themes preview file.
```rust
PrettyPrinter::new()
.grid(true)
.header(true)
.input(
Input::from_reader(Box::new(BufReader::new("Hello world!\n".as_bytes())))
.with_description(Some(
InputDescription::new("String")
.with_kind(Some("built-in")),
)),
)
.print()
.unwrap();
```
- `InputKind::ThemePreviewFile` no longer exists.
=> Make InputDescription into API, remove special input kind for theme previews.

README.md
Clarify the requirements for automatic syntax highlighting when reading
input from stdin. Fixes #1028.
=> Clarify stdin syntax highlighting in the README

src/bin/bat/main.rs, src/syntax_mapping.rs
This addresses issue https://github.com/sharkdp/bat/issues/1024 and adds any configurations specified in `--map-syntax` (including those specified in config) as well as all defaults to the `--list-languages` output.
=> Issue #1024 -- Gets all configured mappings for --list-languages

README.md
For me the default pager is `most` and as the result the text will be pushed to `most` instead of `less`. This change also shows to the user that they can configure the pager according to their preference.
=> Clarified which pager is used in docs

CHANGELOG.md, src/assets.rs, src/bin/bat/main.rs, src/syntax_mapping.rs
Now the each outputted extension should be unique to only one language. Below is the diff output of the old `bat --list-languages` and new `bat --list-languages`.
```diff
13c13
< C:c,h
---
> C:c
49c49
< GLSL:vs,fs,gs,vsh,fsh,gsh,vshader,fshader,gshader,vert,frag,geom,tesc,tese,comp,glsl
---
> GLSL:vs,gs,vsh,fsh,gsh,vshader,fshader,gshader,vert,frag,geom,tesc,tese,comp,glsl
70,71c70,71
< JavaScript:js,htc
< JavaScript (Babel):js,mjs,jsx,babel,es6,cjs
---
> JavaScript:htc
> JavaScript (Babel):js,mjs,jsx,babel,es6,cjs,*.js
92,93c92,93
< Objective-C:m,h
< Objective-C++:mm,M,h
---
> Objective-C:m
> Objective-C++:mm,M
119c119
< Ruby Haml:haml,sass
---
> Ruby Haml:haml
123c123
< Sass:sass
---
> Sass:sass,*.sass
```
But since #1035, some of the output is appearing in the form `Lang ext, *.ext`. …
=> Handle file extension conflicts in --list-languages (#1076)

CHANGELOG.md, assets/manual/bat.1.in
This pull request adds a small section to the `bat.1` manpage on installing custom themes and syntaxes.
It also adds a "more information" section that links to the `bat` GitHub repo.
**Manpage (`batman`):**
**Manpage (`man`):**
=> Add custom languages/themes sections to manpage

.github/workflows/CICD.yml
The main difference is that by default v2 uses `--depth=1`.
=> CI: use checkout v2

CHANGELOG.md, src/bin/bat/clap_app.rs
From a TODO in #1211. Kept wording the same as in `fd` for consistency.
=> Add after_help NOTE to refer to detailed help (and vice versa)

README.md
Was already published on `Homebrew on Linux` by someone else, 
not sure why this isn't already mentioned inside the README 🤔🙂
btw the following link to the `Homebrew on MacOS` formula seems to be wrong 🧐
```
You can install `bat` with [Homebrew](http://braumeister.org/formula/bat):
```
=> Mention Homebrew on Linux 🍺🐧

README.md
When i follow the `Development` part in readme to set up project, the `cargo install --locked` is deprecated with error
`error: Using `cargo install` to install the binaries for the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.`
My setup:
```
cargo --version                                                                                                                                         
cargo 1.45.1 (f242df6ed 2020-07-22)
```
=> Update README.md using cargo install --path

assets/create.sh, tests/benchmarks/comparison.sh, tests/benchmarks/run-benchmarks.sh, tests/syntax-tests/regression_test.sh, tests/syntax-tests/update.sh
This PR adds a few improvements to the shell scripts of this project:
* replacing `#!/bin/bash` with `#!/usr/bin/env bash` to improve compatibility with system where `/bin/bash` is absent (for instance NixOS)
* adding the execution flag
* adding `cd $(dirname $0)` to allow running the scripts from another directory (for instance form root `./tests/syntax-tests/regression_test.sh`). I tested every scripts, some of them were already working without.
=> Shell script improvements

tests/syntax-tests/create_highlighted_versions.py
Referring to issue #1213, some users were seeing traceback when bat was not found on path.
=> Print error message if bat not found on path

assets/manual/bat.1.in
It should be .sublime-syntax instead of .sublime-snytax. I also changed most of "bat" to be "{{PROJECT_EXECUTABLE}}" instead since it seems more consistent. Results looks the same.
=> Fix spelling and use PROJECT_EXECUTABLE more

assets/README.md, assets/syntaxes/02_Extra/INI.sublime-syntax
There's no canonical definition of what's the INI syntax, but Python's `ConfigParser` supports comments after section headers:
```ini
[section] ; comment
```
I also put a PR in upstream (https://github.com/clintberry/sublime-text-2-ini/pull/29), but there have been no merges for a few years.
Also, we already have a modified version here, so a change upstream doesn't take effect.
=> Add support for comments after section headers (closes #1259)

tests/syntax-tests/highlighted/Diff/82e7786e747b1fcfac1f963ae6415a22ec9caae1.diff, tests/syntax-tests/source/Diff/82e7786e747b1fcfac1f963ae6415a22ec9caae1.diff
I used the diff of commit 82e7786e747b1fcfac1f963ae6415a22ec9caae1 to generate the test file (thought that fits here :smiley: and also doesn't need an extra license file that way).
Relates to #1213
(also offtopic, when running `update.sh` it also changed the line endings in `highlighted/Batch/build.bat` from #1279, but I didn't include that in this PR, but tell me if I should add it in a separate commit or create a new PR for that)
=> Add Diff syntax highlight test

CHANGELOG.md, src/controller.rs, src/output.rs
Prevent less from wrapping lines by setting the proper flag when `--wrap=never`.
If the user set a custom value for `--pager`, no additional flag is set.
The implementation is done, I just have to finish testing with the many less versions.
I'm considering building a docker image with the relevant less versions to help testing.
=> Add `-S` flag to less when `--wrap=never` (closes #1255)

tests/.gitattributes
I tried to fix the outgoing change in `highlighted/Batch/build.bat` after running `update.sh`, and as you mentioned in https://github.com/sharkdp/bat/pull/1289#issuecomment-705490210, the source file has CRLF line endings too.
But it looks like this is a git thing, git always commits .bat files with CRLF (because it looks like they don't run correctly with LF line endings, and while we don't want to run these syntax-test files, git doesn't know that). And whatever I tried to make git ignore this and just commit these files with only LF, it ignored all of my tries and just converts the file back to CRLF (`warning: LF will be replaced by CRLF in tests/syntax-tests/highlighted/Batch/build.bat`).
So I started comparing the generated files on a binary level and saw that the difference is only …
=> Set line endings for batch files to LF for syntax-tests

doc/logo-header.svg
Hi there! 👋
Thanks for bat! I use it on a daily basis, whenever I want to see any highlighted content. Be it source code, markup — or things like those nowadays endless yaml files.
So, I thought this would be a nice project to contribute to; being something I use! Maybe I can give something back.
This is how this PR happened. As I am [learning Rust](https://github.com/scorphus/advent-of-code-2018), I though I could take a stab at contributing to some Rust project in the wild. After digging the realms of my memory, bat popped up. Already late into the evening, I openned the repo. Scrolled down a bit. And it appeared! The wide, shiny, white ribbon:
Being shortsighted and therefore a fierce adopter of dark themes, my eyes hurt with that glare. My immediate thought was "that's something I can …
=> Make logo compatible with light and dark themes

tests/syntax-tests/highlighted/reStructuredText/reference.rst, tests/syntax-tests/source/reStructuredText/reference.rst
Using the [reStructuredText quick reference](https://docutils.sourceforge.io/docs/user/rst/quickref.html) I crafted a sample file to be used in syntax regression tests.
=> Adding reStructuredText example file for syntax tests

assets/completions/bat.zsh.in
* Fix completion for `-p` option (closes #1320). The issue was in the `-p/--plain` option (it was expecting an argument), other flags are fine.
* Use prefixed function names to avoid a name clash. Functions in zsh are global, so having a function with the name `_main` isn't good.
=> Fix zsh completion

CHANGELOG.md, src/error.rs, src/output.rs, tests/integration_tests.rs
As mentioned on #1334 `bat` should not be used as a value for `pager`,
this change checks both the balue of `bat` provided as a parameter or
as an environment variable.
=> Throws an error when `bat` is being user as pager.

CHANGELOG.md, CONTRIBUTING.md, CONTRIBUTORS.md, README.md
This changes the README file and adds a new section `Contributors`.
This section includes instructions to remind contributors to make an
update to the changelog.
This relates to #1211
=> From a TODO in #1211. Add documentation for contributors.

src/bin/bat/main.rs
This outputs some help text regarding adding extra themes when --list-themes is run. Initially thought it would go under help for --list-themes or --help but believe this is the best place for it. However happy to move it to a more appropriate location.
Closes #1162
=> Add extra themes help to output

CHANGELOG.md, assets/patches/ShellScript.sublime-syntax.patch
Upstream patch: https://github.com/sublimehq/Packages/pull/2541
closes #1292
=> Highlight ebuild/eclass files with shell syntax

Cargo.lock, Cargo.toml, src/controller.rs, src/input.rs, tests/integration_tests.rs
=> Detect infinite loop when input and output are the same

.github/workflows/CICD.yml
This will resolve the race condition where both the ubuntu 16.04 x64 and ubuntu 18.04 x64 builds generate a `bat-VERSION-x86_64-unknown-linux-gnu.tar.gz` and `bat_VERSION_amd64.deb` and try to publish them. We favour the older release for compatibility.
=> only try to publish one set of archives/packages for linux x64

CHANGELOG.md, tests/syntax-tests/regression_test.sh
The macOS version of mktemp does not recognize the --suffix option.
Using pure -d should work since, it seems [1], macOS 10.11 however.
So to make the script work on macOS, stop using the --suffix option.
The downside is of course that the temporary dir will have an anonymous
name, but I see no risk of confusion given how short-lived the usage of
the dir is, and given the context it is used.
I will not be offended if you disagree, but it is nice to keep things simple.
[1] https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
=> Fix #1443 macOS: regression_test.sh: mktemp: illegal option

diagnostics/info.sh, tests/benchmarks/comparison.sh, tests/benchmarks/run-benchmarks.sh, tests/syntax-tests/update.sh
Fix the following warnings.
[SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155): Declare and assign separately to avoid masking return values.
[SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164): Use cd ... || exit in case cd fails.
[SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230): which is non-standard. Use builtin 'command -v' instead.
=> ShellCheck

CHANGELOG.md, src/bin/bat/main.rs
Hello dear `bat`-team,
I took a look at the issues page and implemented the following: https://github.com/sharkdp/bat/issues/1394;
i.e. this PR makes `bat -L` use its built-in pager.
Since I am new to this whole project I am thankful for any pointers.
One thing I want to discuss: `bat -L` is not the only command producing long output. Shall I implement the same paging logic for these as well?
=> make bat -L use pager

Cargo.toml, src/controller.rs
(I can edit changelog if you want, but this should result in no usage difference nor is it a bugfix)
First off thanks for the great program (not to mention the others you've made that I also use)! I've already recommended it to several of my friends.
So just to give some background I was using `bat` to read a file and pipe the info through some other programs. I was a bit confused why changes to the program weren't mattering when I finally realized that `bat` was limiting the throughput. I decided to see if there were any obvious changes that could help out, and from `cargo flamegraph` I saw a surprising amount of time in `HashSet` contains which I narrowed down to checking the styles for different values. Long story short it was being checked repeatedly in the hot loop leading to a …
=> Remove repeated `contains` calls

tests/integration_tests.rs
This is a regression test for the fix for issue #299. If that fix is
reverted, currently only one test ('header_padding') fails. But that
test is for a different use case, so add a dedicated regression test for
the particular use case issue #299 is about.
=> Add test 'grid_for_file_without_newline' (for issue #299 fix)

src/bin/bat/app.rs
This PR fixes the last **correctness** category of clippy lints, to make the discussions in #1410 simpler to have.
I manually verified that the `-pp` and `-P` flags still work.
(It is worth noting that we have no automated tests that cover the changed code. Probably because it is a bit tricky to test e.g. `PagingMode::QuitIfOneScreen` with `assert_cmd`.)
=> Fix clippy::if_same_then_else warning in --paging=auto logic

src/assets.rs, src/bin/bat/app.rs, src/lib.rs, src/macros.rs
This macro is intended to be package-internal and is not to be
considered part of the public lib API.
Use it in three places to reduce code duplication. However, main reason
for this refactoring is to allow us to fix #1063 without duplicating the
code yet another time.
The macro can also be used for the "Binary content from {} will not be
printed to the terminal" message if that message starts to use eprintln!
instead (if ever).
To trigger/verify the changed code, the following commands can be used:
cargo run -- --theme=ansi-light tests/examples/single-line.txt
cargo run -- --theme=does-not-exist tests/examples/single-line.txt
cargo run -- --style=grid,rule tests/examples/single-line.txt
=> Introduce bat_warning! helper macro

.github/workflows/CICD.yml
Run the linter on the minimum supported rust version; otherwise we will
get lint warnings for things that require a too high Rust toolchain
version to fix.
Allow the following warnings, since we already have them our code:
- clippy::new-without-default
- clippy::match-bool
- clippy::if_same_then_else
Eventually we should fix these lint issues and then disallow them to
prevent them from coming back in other places.
The clippy args used is recommended here:
https://github.com/rust-lang/rust-clippy#travis-ci
I noticed that my PR #1402 passed CICD checks despite having some lint issues, so I thought it would be a good idea to add a linter step to CICD.
I tested the new step in GitHub Actions over at my fork, and it seems to work. You can check here if you want: …
=> Add Clippy linter step to CICD

src/bin/bat/main.rs
To trigger/verify the changed code, run
bat --list-languages   # or -L
This is the last clippy warning in the code that you get if you run
cargo clippy --all-targets --all-features -- --allow clippy::style
so by fixing it it becomes easier to spot when a new warning is
introduced (that does not belong to the clippy category clippy::style).
And by making it easy to spot new warnings, we increase chance of such
regressions not ending up in the code base.
=> bat --list-languages: remove unnecessary format!() call

CHANGELOG.md, src/assets.rs
This will fix #614 by making it clear what is wrong by showing the
following error message:
Failed to load one or more themes from
'/Users/me/.config/bat/themes' (reason: 'Invalid syntax theme
settings')
We also need to add a check if theme_dir.exists(), otherwise an absent
dir will seem like an error:
Failed to load one or more themes from
'/Users/me/.config/bat/themes' (reason: 'IO error for
operation on /Users/me/.config/bat/themes: No such file or
directory (os error 2)')
(This is the same check we already have for syntax_dir.)
=> bat cache --build: Print syntect error message for themes if any

.github/workflows/CICD.yml
Turns out GitHub is clever enough to pick up clippy warnings from us
just running it, and showing them in PRs under a "Unchanged files with
check annotations (beta)" header.
The only warnings currently shown are style warnings, and we agreed we
don't want to risk putting off contributors over style issues. So
explicitly allow (don't warn in the logs for) this category of clippy
lints.
This means that the only clippy categories left that prints warnings
(Warn) are:
clippy::complexity
clippy::perf
And the only category of lints that fails the CI build (Deny) remains to
be:
clippy::correctness
See https://rust-lang.github.io/rust-clippy/master/index.html for a
catalog of all lints.
=> Allow clippy::style lints

.gitmodules, assets/syntaxes/02_Extra/Lean.sublime-syntax, doc/assets.md, tests/syntax-tests/highlighted/Lean/test.lean, tests/syntax-tests/source/Lean/test.lean
Hello -- 
`Lean` is an [interactive theorem prover](https://leanprover-community.github.io/) with a decent sized user base (e.g. its Zulip has... around 3,000 folks idling in it). No users really use Sublime Text, the vast majority of its users use [VSCode](https://github.com/leanprover/vscode-lean), with a small subset using emacs (and an even smaller subset using other), so as I read it it likely doesn't meet the inclusion criteria, but just checking to be sure the above doesn't affect anything (it not really having any Sublime users). I'm sure you get a bunch of these, so certainly no hard feelings if you close it.
Thanks for `bat`!
=> Add Syntax Highlighting for Lean

tests/integration_tests.rs
Right now all tests pass even if we e.g. return
Ok(OutputType::stdout())
instead of doing
.chain_err(|| "Could not parse pager command.")?
so add a test to make sure this functionality don't break.
This is mainly to harden against regressions in #1402, but is self-contained and can be merged right away. As a side-note, we already have a test for `BAT_PAGER=""` so there is no need to add another one.
=> Add integration test for unparsable pager

.github/workflows/CICD.yml
No need for complicated var and set-output logic when we can simply use
matrix.job.toolchain directly.
This is a small and self-contained PR to simplify CICD as requested in #1474.
(Disclaimer: I am new to GitHub Actions myself, but I am comfortable with CI/CD in general.)
=> CICD: Code Coverage: Use matrix.job.toolchain directly

.github/workflows/CICD.yml
The ::set-output syntax is the correct one according to
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter,
so remove duplicates without that syntax.
(I also tested to remove all ::set-output instead as a control, and then the build failed miserably: https://github.com/Enselic/bat/actions/runs/465537465)
This PR is for #1474.
=> CICD: Remove duplicate set-output calls

.github/workflows/CICD.yml
I tried to remove all `use-cross` occurrences, but the two targets this PR were the only ones that builds without `use-cross`.
For reference, here is what happens if you try to remove `use-cross` for all builds: https://github.com/Enselic/bat/actions/runs/464151908
This PR is for #1474.
=> CICD: Remove use-cross when host == target

.github/workflows/CICD.yml
Accoding to #1474:
> We are currently not using the code coverage part.
Since the Code Coverage job usually is the last to finish, I propose we disable it until someone makes it useful to run again. That will reduce the time it takes to complete the CICD pipeline and thus increase productivity for everyone!
=> CICD: Code Coverage: Disable for now

.github/workflows/CICD.yml, Cargo.lock, Cargo.toml, src/bin/bat/clap_app.rs, src/bin/bat/main.rs
This is a draft with a new `--diagnostic` option for `bat` that could eventually replace the `diagnostics/info.sh` script for bug reports (closes #1405). The main part of the work in is in [a new crate called `bugreport`](https://github.com/sharkdp/bugreport), which is in a early stage as well.
I'd be glad for any kind of feedback!
*(see CI output for more examples)*
```
▶ alias bat="bat --style='numbers,grid,header'"     
▶ export BAT_STYLE=numbers,grid
▶ bat --pager="less -RF" src/macros.rs --diagnostic
```
bat 0.17.1
Linux 5.9.14-arch1-1
```bash
bat --style=numbers,grid,header '--pager=less -RF' src/macros.rs --diagnostic 
```
```bash
SHELL=/usr/bin/zsh
PAGER=less
BAT_PAGER=<not set>
BAT_CONFIG_PATH=<not set>
BAT_STYLE=numbers,grid
BAT_THEME=<not set>
BAT_TABS=<not set>
```
``` …
```
=> Add --diagnostic option to bat

.github/workflows/CICD.yml
Make `x86_64-pc-windows-gnu` build again with TOOLCHAIN stable. The referenced issues that are removed have all been closed. There is still some problem with i686-pc-windows-gnu that I haven't managed to figure out how to solve yet, but that's something for later.
I also added an extra commit to remove the unnecessary TOOLCHAIN logic, like I did for Code Coverage.
I did a test-deploy of this change, and got a [green job](https://github.com/Enselic/bat/actions/runs/467135535) and a [release with downloads](https://github.com/Enselic/bat/releases/tag/v0.0.2). Note that `bat-v0.0.2-x86_64-pc-windows-gnu.zip` is a new download due to this PR (🎉 )
This PR is part of the series of PRs for https://github.com/sharkdp/bat/issues/1474.
=> CICD: Build: Enable target x86_64-pc-windows-gnu again

.github/workflows/CICD.yml
There is no usage of `steps.vars.outputs.REF_*` so no need to setup such
things. Also remove setting up REF_NAME and REF_BRANCH env vars, since
they are never read.
For https://github.com/sharkdp/bat/issues/1474
Successful deploy: https://github.com/Enselic/bat/releases/tag/v0.0.4
=> CICD: Build: Remove unused REF_* outputs

.github/workflows/CICD.yml
There is no need for a var and set-output detour.
For  https://github.com/sharkdp/bat/issues/1474
Successful deploy: https://github.com/Enselic/bat/releases/tag/v0.0.3
=> CICD: Build: Use matrix.job.use-cross directly

.github/workflows/CICD.yml
This is a PR for three small commits.
Successful: https://github.com/Enselic/bat/releases/tag/v0.0.5
```
commit f09e437d9d53d9a4d038f36e24b2f354b98f3609
Author: Martin Nordholts <enselic@gmail.com>
Date:   Thu Jan 7 11:06:40 2021 +0100
CICD: Build: Remove unused JOB_DO_TESTING var and output
It is CARGO_TEST_OPTIONS that is used to control testing on
cross-compiled builds, so we can remove JOB_DO_TESTING.
For #1474
commit fbcdcd18543bd9f82c38640e4e89c547eabe7d04
Author: Martin Nordholts <enselic@gmail.com>
Date:   Thu Jan 7 11:05:51 2021 +0100
CICD: Build: Remove unused PKG_suffix output var
Only the env var is used, so output variant is not needed.
For #1474
commit c6673b9ec569c3eeeb1920a2df18b8344bef45ff
Author: Martin Nordholts <enselic@gmail.com>
Date:   Thu Jan 7 11:01:41 2021 +0100 …
```
=> Remove more unused vars and outputs

.github/workflows/CICD.yml
This results in a nicer workflow file that is easier to follow.
Also remove the unneccesary doc row that repeats what is already in the
matrix and that is annoying to keep up to date.
For #1474
Successful deploy: https://github.com/Enselic/bat/releases/tag/v0.0.6
Btw, when deploy failed but build worked, what was wrong? Would be nice to be able to add some kind of deploy-dry-run so we don't have to manually push tags to verify deploy.
=> CICD: Build: Stop building on Ubuntu 16.04

.github/workflows/CICD.yml
The end goal is to upload the same artifacts for a PR as we deploy
during a release, to make a regular PR pipeline as similar as possible
to a deploy.
The first step is to move 'Upload build artifacts' to after 'Package' so
we can upload the same files. Also change the name and artifacts to be
more similar to what we deploy for a release.
For #1474
=> CICD: Build: Make 'Upload build artifacts' more like deploy

.github/workflows/CICD.yml, src/bin/bat/input.rs, src/input.rs, src/output.rs, src/pretty_printer.rs, tests/assets.rs, tests/snapshot_tests.rs, tests/tester.rs
Now that we decided to move to Rust 1.42 as the min. required version, we can fix the remaining clippy "style" suggestions.
=> Fix remaining clippy suggestions

.github/workflows/CICD.yml
This reduces the risk of the build suddenly breaking, and fixes this
current warning:
Ubuntu-latest workflows will use Ubuntu-20.04 soon.
For more details, see https://github.com/actions/virtual-environments/issues/1816
I've used the mapping found at
https://github.com/actions/virtual-environments, so there should be no
actual change in OS versions, only semantically so.
Test deploy looks good: https://github.com/Enselic/bat/releases/tag/v0.0.11
=> CICD: Use fixed OS versions instead of 'latest' ones

.github/workflows/CICD.yml
This PR makes Debian packages be built and published as artifacts for regular PR workflows.
It consists of four steps (commits) that can be code review individually together with respective commit message if the full diff is too confusing.
I think the only controversial change is the addition of `PROJECT_VERSION: "0.17.1"`, but it is already duplicated a lot, and I could not figure out a way to parse it from Cargo.toml in the CI script that was less annoying than duplicating it another time. I am open for ideas though.
The reason we need to do it is that Debian packages can not be built without a version, and since a PR does not contain a version (unlike a tag) we need to use the Cargo.toml version. If we think it is too confusing to reuse the same version string for different builds, we …
=> Also build Debian packages in PR CI workflow

.github/workflows/CICD.yml
As discussed in #1501: try to use `cargo get` to extract the crate metadata from `Cargo.toml` automatically.
GitHub Actions documentation on setting env variables dynamically: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
Ref: #1474 
Edit: Looks like this works as expected. This is how the environment looks like *after* the "Extract crate information" step:
```yaml
env:
MIN_SUPPORTED_RUST_VERSION: 1.42.0
PROJECT_NAME: bat
PROJECT_VERSION: 0.17.1
PROJECT_MAINTAINER: David Peter <mail@david-peter.de>
PROJECT_HOMEPAGE: https://github.com/sharkdp/bat
```
=> CICD: Use 'cargo get' to extract crate metadata

.github/workflows/CICD.yml
Since we run clippy on Rust 1.42.0 we still get warnings about the
presence of clippy::match_bool lints. That lint has been moved from
'Style' to 'Pedantic' in Rust 1.45.0 and onwards however, so let's
silent it in our clippy runs too.
See discussion in https://github.com/sharkdp/bat/pull/1494
=> Explicitly allow clippy::match_bool until we bump MSRV

.github/workflows/CICD.yml
Make sure to ignore whitespace changes when diffing.
For #1474
(I'm skipping to test-deploy a release from now on, since we have started to build all release/deploy artifacts with every PR. One can manually sanity-check that deploy still works by checking for 16 artifacts that seems to have correct names and file sizes)
=> CICD: Build: Split up into separate 'Debian package' step

CHANGELOG.md, src/pretty_printer.rs
- The following `PrettyPrinter` methods have been removed (they were previously deprecated):
- `input_stdin_with_name`
- `input_from_bytes_with_name`
- `input_from_reader_with_name`
- `vcs_modification_markers` (if the `git` feature is not enabled)
=> Remove deprecated PrettyPrinter methods

CHANGELOG.md, assets/syntaxes/02_Extra/Manpage.sublime-syntax, assets/syntaxes/02_Extra/syntax_test_man.man
This PR updates the Manpage syntax to fix #1511 and also highlight environment variables, i.e. like those beginning with a `$` sign in `man systemd`
=> Add support for env vars and manpage refs with dots to Manpage syntax

CHANGELOG.md, README.md
As discussed in #1519, the batcat snap package is too problematic for
official endorsement, so withdraw recommendation from README.me (and
remove section from CHANGELOG.md since a release with it has not been
made yet).
For now this MR should just be seen as a sketch of how we could go about doing it, in case we end up choosing this path.
=> README.md: Warn about buggy snap packages

.github/workflows/CICD.yml
So that we don't have to duplicate that logic in both 'Debian package'
and 'Package' steps.
For #1474
I have sanity-checked/compared a selection of extracted Debian and regular packages produced from these changes with the ones from the official 0.17.1 release, and seems like nothing is broken.
Only differences were intentional and not related to my changes (Using `/usr/share/doc/bat-musl/` instead of `/usr/share/doc/bat/` in musl .deb, and the addition of the `CHANGELOG.md` in both package types)
=> CICD: Build: Introduce and use new 'Strip release bin' step

src/bin/bat/main.rs, src/config.rs, src/less.rs, src/output.rs
As we briefly mentioned in #1098, hardcoded paths to `less` were a bit of a pain point for both the version check and the `--diagnostic` option. This is a quick pull request that fixes both of them.
=> Fixes to use the user-specified pager for less version check and diagnostic.

.github/workflows/CICD.yml
A common staging dir confuses more than it helps, so let each package
step take care of its own staging dir.
For #1474
Test deploy (with equivalent commit tree, I just modified commit msg) looks good: https://github.com/Enselic/bat/releases/tag/v0.0.13
=> CICD: Build: Use package-specific staging dir

.github/workflows/CICD.yml
Here are the 3 last commits towards the goal of getting rid of the ‘Initialize workflow variables’ step mentioned in the second bullet in #1474.
Full diff turned out a bit confusing, but reviewing each commit individually should make it crystal clear what is happening.
Test deploy look good: https://github.com/Enselic/bat/releases/tag/v0.0.14
=> CICD: Build: Split up ‘Initialize workflow variables’ step

.github/workflows/CICD.yml
Without this change, creating a PR triggers all jobs to run twice. Once
due to a push event and once due to a pull_request event.
Change to only trigger jobs due to push when pushing a tag or to the
master branch, to avoid duplicate jobs for each PR.
Triggering for tags confirmed to still work: https://github.com/Enselic/bat/actions/runs/586250776
=> CICD: Don't run jobs twice in PRs

CHANGELOG.md, src/bin/bat/config.rs, tests/integration_tests.rs
Do not ignore `BAT_CONFIG_PATH` if it doesn't exist. Both when
generating a new config file with `--generate-config-file` and
when attempting to read the config.
Also, provide a better error message in case the file can not
be created.
closes #1550
=> Do not ignore non-existent BAT_CONFIG_PATH

.github/workflows/CICD.yml
Which is useful when you want to test a fix without creating a PR for
it.
Disclaimer: I put this in master in my fork, but it did not seem to work. I suspect it has to be in the mother project. From what I understand, this change should be enough to allow CICD piplines to be created manually, which is always useful.
Source: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
Maybe we can merge this and simply see if it works?
=> CICD: Add workflow_dispatch to enable manual builds

tests/integration_tests.rs
As a complement to #1556 to prevent #1550 from coming back.
The test purposefully fails if ca60937c2e is reverted.
=> integration_tests.rs: Add test config_location_when_generating

Cargo.lock, Cargo.toml, src/assets.rs, src/controller.rs, src/input.rs, tests/integration_tests.rs
Fixes #1503
This implements the exact logic for circle detection from `cat` for `bat`. To test this out yourself, you will have to get the newest version from the [pull request](https://github.com/niklasmohrin/clircle/pull/6) on the `clircle` repository and replace the `clircle` dependency in the `Cargo.toml` with the path to your local copy.
I will still have to fix the tests and see what to do with windows. Now that the posix approach (only error if program will provably fail later on) is taken here, we will have to investigate the situation on windows more closely.
I might still change things, there are breaking changes in `clircle` already, so there's no reason to hold back on changes over there.
Let me know, what you think and if you know anything about this on windows!
=> Use more conservative circle detection

CHANGELOG.md, src/assets.rs, src/bin/bat/app.rs, src/bin/bat/input.rs, src/bin/bat/main.rs, src/diff.rs, src/input.rs, src/pretty_printer.rs
Using `Path`s for paths expresses intent more clearly.
Drive by change mostly, I just accidentally fell into non-utf8 arguments pit :)
=> Improve readability

.github/workflows/CICD.yml
Now that we are on MSRV 1.45, there is no need to "backport" the change
that reclassified clippy::match_bool as "pedantic".
=> CICD: Remove explicit allow of clippy::match_bool since MSRV 1.45 bump

.gitmodules
Using SSH to fetch the submodule was causing build failures for me, and as mentioned in [#1581](https://github.com/sharkdp/bat/pull/1581), this should be changed to HTTPS
=> Change TheClams/SystemVerilog submodule to use HTTPS

CHANGELOG.md, src/bin/bat/main.rs
So issues like #1586 are easier to troubleshoot.
=> Include LESS in --diagnostic

src/less.rs
Less 581.2 is here, and it has a ".2" in the version string, which can't
be parsed as a usize.
Update the check to find a non-digit character rather than a space. This
ignores the minor version, but parses the major version correctly.
=> Fix less version parsing for minor versions of less

CHANGELOG.md, src/assets.rs, src/pager.rs, src/pretty_printer.rs, src/printer.rs
The Minimum Supported Rust Version (MSRV) for `bat` is 1.45.0. Setting `msrv = "1.45.0"` in `.clippy.toml` (not part of the repository) and running `cargo clippy` emits 7 warnings. These are proposed fixes to said warnings. If there are any lints we would rather allow, I can revert the relevant commit(s) and add the appropriate lint attribute(s).
Also, do you think we should create `.clippy.toml`/`clippy.toml` and set the MSRV to ensure consistency amongst contributors?
=> Fix Clippy lints

README.md
Quick and dirty fix for #1666. I think the whole "Using a different pager" section would probably benefit from some restructuring and cleanup, but with this PR, we at least have _something_ in the readme that informs the user of PAGER + most/more, which decidedly is better than _nothing_.
=> README.md: Mention that PAGER is ignored if set to more or most

assets/syntaxes/02_Extra/Fstab.sublime-syntax
This is mentioned in https://github.com/sharkdp/bat/pull/696#issuecomment-544692236, but somehow not implemented.
=> Highlight mtab files with fstab highlighting

src/pretty_printer.rs
Otherwise Rust 1.53.0 gets confused during `cargo doc` because it thinks
we want an actual URL:
warning: this URL is not a hyperlink
--> src/pretty_printer.rs:331:40
|
331 |     /// The title for the input (e.g. "http://example.com/example.txt")
|                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<http://example.com/example.txt>`
|
= note: `#[warn(rustdoc::bare_urls)]` on by default
= note: bare URLs are not automatically turned into clickable links
It was perhaps also a bit confusing to give an URL as an example in the
first place, because according to our own API example
`examples/inputs.rs` it is meant to be more a free-text thing.
=> pretty_printer.rs: Don't use a URL as an example Input title

.github/workflows/CICD.yml, .gitignore, CHANGELOG.md, assets/completions/bat.bash.in, build.rs
Closes https://github.com/sharkdp/bat/issues/1010
This implementation is self contained and does not require https://github.com/scop/bash-completion. If a dependency on it would be ok, adding it would make it possible to clean this up some, and would gain easy support for completing long options separated by `=` (which this one doesn't currently, and I'd rather not duplicate the code for that). Let me know if that would be desirable and I can adjust this.
=> Add bash completion

.github/workflows/CICD.yml
Minor changes to keep the CI/CD script roughly  in sync with the one of https://github.com/sharkdp/pastel (https://github.com/sharkdp/pastel/pull/142)
I am hoping to use this as a template for my other Rust projects as well. Most of them are still on Travis CI :slightly_frowning_face:
=> CICD: sync with pastel, minor changes

src/assets.rs, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.bak, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.dpkg-dist, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.dpkg-old, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.in, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.in.in, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.old, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.orig, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.orig~, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.rpmnew, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.rpmorig, tests/syntax-tests/highlighted/Ignored suffixes/test.rs.rpmsave, tests/syntax-tests/highlighted/Ignored suffixes/test.rs~, tests/syntax-tests/highlighted/Ignored suffixes/test.unknown~, tests/syntax-tests/source/Ignored suffixes/test.rs.bak, tests/syntax-tests/source/Ignored suffixes/test.rs.dpkg-dist, tests/syntax-tests/source/Ignored suffixes/test.rs.dpkg-old, tests/syntax-tests/source/Ignored suffixes/test.rs.in, tests/syntax-tests/source/Ignored suffixes/test.rs.in.in, tests/syntax-tests/source/Ignored suffixes/test.rs.old, tests/syntax-tests/source/Ignored suffixes/test.rs.orig, tests/syntax-tests/source/Ignored suffixes/test.rs.orig~, tests/syntax-tests/source/Ignored suffixes/test.rs.rpmnew, tests/syntax-tests/source/Ignored suffixes/test.rs.rpmorig, tests/syntax-tests/source/Ignored suffixes/test.rs.rpmsave, tests/syntax-tests/source/Ignored suffixes/test.rs~, tests/syntax-tests/source/Ignored suffixes/test.unknown~
For example, fall back to `foo.extension` for `foo.extension~`, `foo.extension.orig`, `foo.extension.in.in` etc.
Rust newbie alert, likely clumsy/not idiomatic, but appears to work. Critique/guidance very much welcome, for example redundant/repeated conversion between `OsStr`, `Path`, and `str` doesn't seem that clean to me.
=> Find syntax ignoring known backup/template filename suffixes

src/assets.rs, src/bin/bat/assets.rs
When prototyping for https://github.com/sharkdp/bat/issues/951 I play around with introducing a new asset called `lookup.bin`. I bumped into some inconvenient code duplication that I de-duplicate in this PR. I think it is a sensible PR regardless of how the prototyping falls out.
I might appear to have placed the helper functions in odd places, but it is to make the diff as easy to review as possible. We can always move them around once the initial code review is done, in case you find the current placement of them unacceptable. FWIW, I personally can live with their current placement.
The change should be low-risk since it tries to make no behavioural changes. I still plan to do a thorough verification of the changes after the first code review round though.
=> De-duplicate some themes.bin and syntaxes.bin related code

src/assets.rs, src/printer.rs
Since we only modify `pub(crate)` items, the stable bat-as-a-library API is not
affected.
This takes us one step closer to making SyntaxSet lazy-loaded, which in turn
takes us one step closer to solving #951. This change has proven useful in the prototype I made to improve startup time, see https://github.com/sharkdp/bat/issues/951#issuecomment-882098532
By my estimation, it will always be convenient to have the full SyntaxSet available, for things such as `--list-languages`. So regardless of the fate of the prototype in #951, I think this will end up being a sensible change. Because we only want to load the full syntax set when necessary (since it is slow).
=> HighlightingAssets: Encapsulate syntax_set behind a getter

src/assets.rs
It already now reduces code duplication slightly, but will become even more
useful in the future when we add more complicated logic such as lazy-loading. See e.g. https://github.com/sharkdp/bat/issues/951#issuecomment-882098532.
=> HighlightingAssets: Introduce private fn new() helper

assets/patches/Markdown.sublime-syntax.patch
Recently GitHub added support for
````
```rs
fn main() {}
```
````
code blocks rendering as Rust:
```rs
fn main() {}
```
where `rs` is an alternative to the previous keyword `rust`.
=> Add `rs` identifier for Rust code blocks in Markdown

CHANGELOG.md, src/assets.rs
When [measuring performance](https://github.com/sharkdp/bat/pull/1747#issuecomment-886392521) of lazy loading, I noticed a somewhat surprising discrepancy for loop-through performance with and without cached assets. So I looked into possible causes for that and noticed we can make loading of cached assets faster. (Remember: we still eagerly load themes.bin in the above lazy-load PR.)
Using `BufReader` makes sense for large files, but I am convinced assets are never large enough (until proven otherwise) to require buffering. It is significantly faster to load the file contents in one go, so let's do that instead.
The numbers are identical when loading integrated assets. Here are the performance measurements when loading assets that are identical to the integrated assets. I am comparing git …
=> Make loading of cached assets closer in performance to integrated assets

src/assets.rs
To make the code easier to understand and change.
=> HighlightingAssets::get_extension_syntax(): Split up into smaller methods

CHANGELOG.md, src/assets.rs, src/bin/bat/main.rs, src/pretty_printer.rs, src/printer.rs, tests/no_duplicate_extensions.rs
Or rather, introduce new versions of these methods and deprecate the old ones.
This is preparation to enable robust and user-friendly support for lazy-loading.
With lazy-loading, we don't know if the SyntaxSet is valid until after we try to
use it, so wherever we try to use it, we need to return a Result. See discussion
about panics in #1747.
=> HighlightingAssets: Make .syntaxes() and .syntax_for_file_name() failable

assets/completions/bat.zsh.in, src/bin/bat/app.rs, src/bin/bat/assets.rs, src/bin/bat/clap_app.rs, src/bin/bat/main.rs, src/config.rs, tests/integration_tests.rs
The main use-case I have in mind for this flag is to make it easy to parameterize hyperfine (`hyperfine --parameter-list assets --no-custom-assets, 'bat {assets} examples/simple.rs'`) to compare performance between custom vs integrated assets, as we work on #951. But I would be surprised if it would not come in handy for other uses as well in the future.
I choose to name the arg `--no-custom-assets` rather than `--no-cache` in order to be more future-proof with upcoming changes. Since it is a hidden arg, I figured it would be OK to do it like this. I do not mention it in CHANGELOG.md though, since I don't think we need to make it publicly visible at this point. But let me know if you disagree!
=> Support a hidden arg --no-custom-assets that skips loading assets from the cache

CHANGELOG.md, Cargo.lock, Cargo.toml, src/assets.rs
`HighlightingAssets::get_syntax_set()` is never called when e.g. piping the `bat` output to a file (see `Config::loop_through`), so by loading the `SyntaxSet` only when needed, we radically improve startup time when it is not needed.
On my low-end machine, I get the following numbers when doing
`time bat tests/examples/multiline.txt > /tmp/output.txt`:
**git master**
```
0,09s user 0,00s system 93% cpu 0,103 total
```
**git master + this PR**
```
0,01s user 0,00s system 63% cpu 0,026 total
```
We can also benchmark with `hyperfine` , in which case we don't need to redirect the output manually, because the internal redirection of `hyperfine` is enough to trigger loop-through mode:
`hyperfine --export-markdown /dev/tty 'bat tests/examples/multiline.txt'`
**git master**
| Command | Mean [ms] …
=> Reduce startup time in loop-through mode by 80%-90%

src/assets.rs
Mainly to prepare for potential lazy-loading in the future to improve startup performance. Like we did for `syntax_set`.
I currently don't plan on making `ThemeSet` lazy-loaded, because the impact of that is negligible compared to other things we can do. But in case we want to do it later, it's nice to have the code prepared like this.
=> HighlightingAssets: Encapsulate theme_set behind a getter

src/assets.rs
And instead of taking a get_syntax_set() detour to return a
name that represents "no syntax", return such a string directly.
=> assets::tests: Add get_syntax_name() helper

.github/workflows/CICD.yml
To avoid that earlier cargo commands "fixes" `Cargo.lock` before cargo commands
with `--locked` has a chance to check if it is up to date.
It would have been nicer with something like a CARGO_ARGS env var to make sure it is passed everywhere, but I could not find support for such an env var. So this PR just adds `--locked` everywhere.
=> CICD: Pass --locked to all cargo commands

Cargo.lock, Cargo.toml, src/assets.rs
Upgrade to syntect 4.6.0 and add a warning to stdout when building assets from files and some context references are unresolved. Fixes #1616 and makes it easier to work on #915 and prevent such cases occurring again in future :)
=> Warn when building assets from files if some referenced contexts are missing

src/input.rs
This fixes all of these lint warnings:
https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison
They only appear in recent versions of clippy. Not on our MSRV.
=> Use assert!(..) instead of assert_eq!(true, ..)

tests/integration_tests.rs
I'm playing around with code coverage in nightly (see https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/instrument-coverage.html) and from that noticed that we have no automated tests for `--diagnostic`.
So add a simple sanity check test for `--diagnostic` so we catch in CI if that feature breaks completely.
For future reference (not least for myself :P), here are some commands that can be used to generate code coverage data for `bat` **and** its dependencies:
```
rustup default nightly
rustup update nightly
cargo install cargo-binutils
rustup component add llvm-tools-preview
export LLVM_PROFILE_FILE="/tmp/coverage/%h-%p-%m.profraw"
rm -rf /tmp/coverage
cargo clean
RUSTFLAGS="-Z instrument-coverage" cargo test
./target/debug/bat cache --build --source=assets --blank …
```
=> integration_tests: Add diagnostic_sanity_check()

src/assets.rs, src/lib.rs, src/syntax_dependencies.rs
This will eventually allow us to improve the startup speed of bat. See #951.
It adds code to analyze dependencies between `SyntaxDefinition`s. It currently comes up with the following  list of independent syntaxes.
One thing I'm curious about is if you think this list, and the code I use to produce it, looks reasonable? Or can you spot any obvious dependencies that it fails to find?
I'm sure we're going to have to tweak the code that does the analysis, but it would be nice to get the basics of it in place so we can iterate on it.
<details>
<summary>List of independent syntaxes</summary>
<p>
```
Independent SyntaxSets:
["Plain Text"]
["ASP", "HTML", "JavaScript (Babel)", "GraphQL", "Regular Expressions (Javascript)", "CSS", "HTML (ASP)", "ASP"]
["HTML (ASP)", "ASP", "HTML", "JavaScript …
```
=> Add code for analyzing dependencies between syntaxes

CHANGELOG.md, src/assets.rs, src/bin/bat/main.rs, src/printer.rs
Here comes what I think will be the most controversial change on the #951 journey, because it has the highest impact on the bat-as-a-library API. Let me know what you think about it.
To improve startup performance, we will later load smaller `SyntaxSet`s instead of one giant one. However, the current API assumes only one `SyntaxSet` is ever used, and that that implicitly is the `SyntaxSet` from which returned `SyntaxReference`s comes.
This change changes the API to reflect that `SyntaxSet` and `SyntaxReference` are tightly coupled, and enables the use of several `SyntaxSet`.
I think it will make sense to add a helper method to reduce the boilerplate a bit, but I would like to get early feedback on the change itself before I do that.
=> When returning a SyntaxReference, also return the SyntaxSet that contains it

.github/workflows/CICD.yml, Cargo.lock, Cargo.toml, src/bin/bat/main.rs
I frequently find myself having to rebuild the whole project (.e.g when switching between MSRV, stable, nightly). Because of that, it is useful if a rebuild goes fast. Two features in particular contribute significantly to build time, and those are `git` and `bugreport` (with `git_hash`).
This PR introduces a feature called `quick-build-application` that allows the app to be built without the above features. On my system, that results in ~25% faster builds:
```
hyperfine --max-runs 2 --time-unit second --export-markdown /dev/tty --parameter-list feature quick-build-application,full-application --prepare 'cargo clean' 'cargo build --no-default-features --features {feature}'
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `cargo build …
=> Cargo.toml: Introduce 'quick-build-application' feature

src/bin/bat/clap_app.rs, tests/integration_tests.rs
I frequently find myself intuitively passing `--no-pager` to bat, only to be equally frequently slightly annoyed that it does not work.
Then I by accident found that it seemed like it *should* work, since we set it up in `clap_app.rs`. It used to work actually, before it stopped working with c264f747.
I'm fine with keeping `--no-pager` hidden, but I would really prefer if it worked, so here is a PR to make it work again. (Since it is hidden, I am skipping updating `CHANGELOG.md`.)
=> Make --no-paging and --no-pager work again, plus regression tests

CHANGELOG.md, src/bin/bat/directories.rs, tests/integration_tests.rs
This PR closes issue #1727
I added a nearly-identical test case to one that already exists, for verbosity's sake I left it there but I understand if we'd want to wrap the new test case into an existing one.
=> Recognize $BAT_CONFIG_DIR and give it precedence over $XDG_CONFIG_HOME

.github/workflows/CICD.yml, Cargo.toml, src/assets.rs, src/assets_metadata.rs, src/bin/bat/main.rs, src/config.rs, src/error.rs, src/lib.rs
The main short-term benefit of this PR is to make building `minimal-application` (previously called `quick-build-application`) even faster.
But it also opens up a major long-term possibility:
* If we end up creating a separate `bat-assets` binary to build assets, we can still allow users to optionally keep the current capability in the main app
For the curious, here are some numbers, comparing `minimal-application` with `application` for stripped release builds. Note that I am including https://github.com/trishume/syntect/pull/345 in below numbers:
| variant               | stripped release binary size | dependencies to build |
| ----------------------|------------------------------|-----------------------|
| `minimal-application` | 3,5M                         | 121                   |
| …
=> Make 'build-assets' an optional capability for application

doc/release-checklist.md
This adds some documentation concerning the release of new `bat` versions. The first commit is my partially outdated version. Let's discuss which steps can be removed / should be changed / should be added.
=> Add release checklist

src/bin/bat/main.rs
To make it easier to debug problems like #1806 in the future.
=> Add LANG and LC_ALL to --diagnostics output

CHANGELOG.md, assets/manual/bat.1.in, src/bin/bat/clap_app.rs, src/line_range.rs
Working with long files and using line range can be hard sometimes. For example if we want to see just a few lines after line `55478`, we would need to write both numbers which are large, and that can lead to mistakes.
It's much easier to write `55478:+5` or `55478:+30`.
This is influenced by similar syntax in `git` for `log` sub-command with `-L` argument.
=> Support for line range plus syntax

CHANGELOG.md, src/assets.rs, src/bin/bat/main.rs, src/build_assets.rs, src/lib.rs
In the current code base, it is necessary to create a temporary `HighlightingAssets` instance to be able to build assets.
This PR moves the code to build assets to its own place, independent of `HighlightingAssets`. This allows us to significantly simplify `HighlightingAssets` since we can make `SerializedSyntaxSet` mandatory.
This also makes sense on a conceptual level. When building assets, it will never be necessary to also highlight source code. So it makes sense to stop using `HighlightingAssets` for this.
This means that we no longer allow clients of our API to build assets during startup. But that is very slow, and I can't imagine why anyone would want to do that. And this simplification is worth a lot in terms of flexibility. So IMHO it is worth having to deprecate API.
I …
=> Don't take a HighlightingAssets detour to build assets

.github/workflows/CICD.yml
I frequently find myself struggling to find the CI matrix job I'm after. This is partly because the name is truncated and does not display the full `target` (in my desktop at least). Since the OS can easily be seen via the `target`, I think it make sense to put `target` first.
To make the right target as easy as possible to find, I have sorted build job by target. Note that GitHub keeps the order from the .yml in the web UI.
Also remove the disabled windows target which is just in the way.
P.S. I get a deja vu feeling, did we already discuss this? :thinking: 
Before and after screenshots:
=> CICD: Swap target and os in matrix job name

.github/workflows/CICD.yml, tests/syntax-tests/BatTestCustomAssets.sublime-syntax, tests/syntax-tests/highlighted/BatTestCustomAssets/NoColorsUnlessCustomAssetsAreUsed.battestcustomassets, tests/syntax-tests/source/BatTestCustomAssets/NoColorsUnlessCustomAssetsAreUsed.battestcustomassets, tests/syntax-tests/test_custom_assets.sh
Our current CI pipeline does not regression test the custom assets functionality at all. We get a [green](https://github.com/Enselic/bat/runs/3459232947) pipeline even if we replace `HighlitingAssets::from_cache` with this:
```rust
pub fn from_cache(cache_path: &Path) -> Result<Self> {
#[allow(unused_variables)]
let res = Ok(HighlightingAssets::new(
SerializedSyntaxSet::FromFile(cache_path.join("syntaxes.bin")),
asset_from_cache(&cache_path.join("themes.bin"), "theme set")?,
));
panic!("does this code run in CI?");
#[allow(unreachable_code)]
res
}
```
This PR adds code to regression test the custom assets functionality. It can be seen as preparatory work for the verification of #1825, but is of course useful on its own.
=> Add regression testing for the custom assets functionality

tests/integration_tests.rs, tests/syntax-tests/create_highlighted_versions.py
We want to make sure that all of our test environments are clean from
possible outside modification. This consolidates the list of used
environment variables in Rust-based and Python-based integration tests.
Note that there is also a similar list in `src/bin/bat/main.rs` which
is even more exhaustive (for bug report collection). However, some
of these variables can not possibly have an effect on test environments.
=> Consolidate environment variable lists in tests

src/assets.rs, src/bin/bat/main.rs, src/config.rs, src/controller.rs, src/input.rs, src/less.rs, src/printer.rs, src/syntax_mapping.rs
Summary:
- Remove some redundant `.iter()`/`.into_iter()` calls
- Reduce nesting in `if-else` blocks that can be easily short circuited
- Use deref coercion to avoid some `.as_...()` calls
=> Add small refactorings

src/assets.rs, tests/examples/regression_tests/first_line_fallback.invalid-syntax, tests/integration_tests.rs
The first commit makes the following work via first_line_match:
```
bat --map-syntax='*.invalid-syntax:InvalidSyntax' tests/examples/regression_tests/first_line_fallback.invalid-syntax
```
and adds a regression test for it.
The second commit simplifies the code, thanks to the fix in the first commit. It is funny how adding features can result in simpler code.
All regression tests pass, but we don't seem to have that many regression tests for `--map-syntax`, so I might add some more after code review of this.
(The reason I am bothering to simplify the code at all is of course to make #951 easier to implement.)
=> Simplify HighlightingAssets::get_syntax() first_line logic

src/assets.rs
This is three commits. The last one is perhaps a matter of taste, but the problem with the `absolute_path` variable was that it did not necessarily contain an absolute path. Rather then renaming it to, say, `maybe_absolute_path`, I inlined it. That way one does not have to come up with a good name. It was only used once anyway.
=> HighlightingAssets: Simplify absolute_path code

src/assets.rs
This is just another code simplification without changing any behavior.
It consists of two commits. You might find it easier to understand what is going on by reviewing each commit individually rather than the full diff. But the full diff is pretty nice too.
=> HighlightingAssets: Inline find_syntax_by_file_name[_extension](), and simplify

src/assets/build_assets.rs
Progress on #951 continues, and I now have work-in-progress code where `syntaxes.bin` has been removed, and every syntax is present in `minimal_syntaxes.bin`. Notably, without duplicates, so the size of `minimal_syntaxes.bin` is the same as `syntaxes.bin`, differing only by some tens of kbs.  See https://github.com/Enselic/bat/pull/38.
While there still are problems to solve, I am confident in some parts of the code, and will ~~start~~ continue to create separate PRs to take the code base in that direction. (Actually, #1856 is also this kind of PR.)
This PR consists of three commits. The first commit just renames stuff in preparation for the third commit. The second commits just moves code around a bit to fit better with the third commit. The "real" code is in the third commit. It adds …
=> Track dependents for each syntax

tests/syntax-tests/create_highlighted_versions.py
The syntax highlighting regression tests can be trivially parallelized.
On my notebook (8 core), this results in a 3.9x speedup.
=> Parallelize syntax regression tests

src/assets/build_assets.rs, src/assets/build_assets/graphviz_utils.rs
Also include a couple of fixes for dependency analysis (that does not affect the existing `minimal_syntaxes.bin` file) that I discovered by looking at the generated file. (There is still a problem left with dependencies being tracked on "self", that I might fix in some other PR.)
Here is a map of current syntax dependencies (click to enlarge):
Instructions on how to build a PNG yourself is included in the code as a comment, but I also duplicate it here for convenience:
```
% sudo apt install graphviz
% BAT_SYNTAX_DEPENDENCIES_TO_GRAPHVIZ_DOT_FILE=/tmp/bat-syntax-dependencies.dot cargo run -- cache --build --source assets --blank --target /tmp
% dot /tmp/bat-syntax-dependencies.dot -Tpng -o /tmp/bat-syntax-dependencies.png
% open /tmp/bat-syntax-dependencies.png
```
=> Enable optional dump of syntax dependencies to Graphviz dot file

src/assets.rs, src/input.rs
This refactoring makes code easier to reuse across e.g. `HighlightingAssets` and `MinimalAssets`, if needed (depends on what route we take). But it is a sensible refactoring regardless.
=> src/assets.rs: Extract helper method OpenedInput::path()

CHANGELOG.md, src/assets.rs, src/bin/bat/main.rs
We do this mainly to reduce duplication of logic. The move to adjust the public API is more of a side effect. It so happens that adjusting the public API also simplifies the code.
One of the reasons this refactoring works is that the `.file_name()` of a `file_name` is `file_name` unchanged:
```
#[test]
fn file_name_of_file_name_is_same() {
let path = Path::new("test.rs");
let expected = Path::new("test.rs");
assert_eq!(path.file_name().unwrap_or_default(), expected);
}
```
=> HighlightingAssets: Extract new public API method get_syntax_for_path()

src/assets.rs, src/printer.rs
By forwarding the task to find the `Plain Text` syntax to `assets`. Not only does
the code become simpler; we also get rid of a call to `self.get_syntax_set()`
which is beneficial to the long term goal of replacing `syntaxes.bin` with
`minimal_syntaxes.bin`.
Note that the use of `.expect()` is not a regression in error handling. It was previously hidden in `.find_syntax_plain_text()`: https://docs.rs/syntect/4.6.0/src/syntect/parsing/syntax_set.rs.html#288-291
=> src/printer.rs: Simplify Plain Text fallback code

.github/workflows/CICD.yml
Follow the same route as for the fish/zsh completions in `.github/workflows/CICD.yml`.
Closes #1733
=> Add bash completion to deb package

README.md
`bat` is available in the Ubuntu repositories for a while now and in Debian `stable` since August.
Let's update the doc accordingly.
=> Update the doc for Ubuntu and Debian

.gitmodules, CHANGELOG.md, assets/syntaxes/02_Extra/Racket.sublime-syntax, tests/syntax-tests/highlighted/Racket/test.rkt, tests/syntax-tests/source/Racket/test.rkt
Add syntax files for Racket language.
It is based on [Racket](https://packagecontrol.io/packages/Racket) syntax highlighting plugin, which have more than 10K downloads at packagecontrol.
For the test, I used [some old MIT-licensed code](https://github.com/jubnzv/nix.rkt/blob/master/nix/test.rkt) written by me.
Closes #1884
=> Add Racket syntax

.github/workflows/CICD.yml
Mainly to make it easier to see what went wrong when CI fails.
If this ever gets of out sync with a particular Rust version, we can most likely
save the situation by introducing a `rustfmt.toml` file.
Note that I choose to make the config minimal (e.g. without `name`). I think it does not make things harder to understand. In fact, I think it makes things easier to understand and maintain. I also use the default Rust installation instead of installing our own. That's just unnecessary to do in this case.
=> CICD: Make the 'cargo fmt' check a toplevel job

src/bin/bat/main.rs, src/lib.rs
The deny also applies recursively to submodules.
=> Deny unsafe code in lib and bin

README.md
- fix bad abbreviation and bad grammar 
- add whitespace before code blocks for consistency with first half of the doc and readability
=> docs: fix up README

README.md
As per #234, #403, #1572, #1823 and #1897, this PR clarifies that `bat` cannot properly handle escape sequences.
=> README.md: Add 'Garbled output' to 'Troubleshooting'

tests/benchmarks/run-benchmarks.sh, tests/benchmarks/test-src/small-Markdown-file.md
Performance characteristics of the file used for the test:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `bat-v0.18.3` | 112.4 ± 1.6 | 109.9 | 116.9 | 3.46 ± 0.16 |
| `bat-minimal_assets.bin` (never managed to solve startup for Markdown files)  | 117.3 ± 1.8 | 114.3 | 120.6 | 3.61 ± 0.16 |
| `bat-syntect-master` (with syntax lazy-loading) | 32.5 ± 1.4 | 30.4 | 38.5 | 1.00 |
Example output of `run-benchmarks.sh`:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `bat` | 10.8 ± 1.2 | 9.7 | 19.4 | 1.00 |
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `bat … small-Markdown-file.md` | 32.3 ± 2.6 | 29.8 | 46.9 | 1.00 |
...
=> run-benchmarks.sh: Add new test 'Startup time with syntax highlighting'

tests/benchmarks/run-benchmarks.sh, tests/benchmarks/test-src/small-CpuInfo-file.cpuinfo
Using Markdown for a startup test is useful since it has so many dependencies on
other syntaxes. So such a test makes sure that lazy-loading of syntaxes work.
It is however also useful to measure the startup time of bat when the time to
load a syntax is very small, and the measured startup time has mostly non-syntax
related causes. Such as:
* Parsing arguments
* Setting up syntax mappings
* Loading themes
This commit adds such a test. It uses the CpuInfo syntax which is very small.
Only 14 lines, compared to the 1581 lines that Markdown is (not including the
size of its included syntaxes).
This command can be used to get an approximation of the size of syntaxes, and
thus how expensive they are to lazy-load:
find -name *.sublime-syntax -print0 | xargs --null wc -l | sort -n -r
Example …
=> run-benchmarks.sh: Add third 'Startup time' variant

.github/workflows/CICD.yml, tests/scripts/license-checks.sh
I have confirmed that the script catches the problem that #1960 fixes.
=> CICD: Add check for accidental inclusion of GPL:ed code

doc/release-checklist.md
I don't think we can do much about transitive dependencies being out of date? So I think we want to run `cargo outdated --root-deps-only`?
=> release-checklist.md: Update `cargo outdated` section with link and arg

src/assets.rs, src/bin/bat/app.rs, src/bin/bat/config.rs
Clippy in the newly released Rust 1.57 found some new lints. Conveniently, all
of them were fixable with `--fix`.
=> Run `cargo clippy --fix --all-targets --all-features` with Rust 1.57

tests/benchmarks/run-benchmarks.sh
=> run-benchmarks: Benchmark both --wrap=character and --wrap=never

assets/create.sh
I quite frequently encounter this inconvenience:
**Step-by-step:**
1. Make some changes to how assets are built
2. Rebuild assets with `cargo build && PATH="./target/debug:$PATH" assets/create.sh`
3. While assets are built, realize I made a mistake and abort with Ctrl+C
**Expected result:**
Patches are not applied any longer since `create.sh` was aborted
**Actual result:**
Patches are still applied, causing an error when `create.sh` is invoked next time. I usually run `git submodule update --init --force` to get rid of the patches. But then there are always some `.rej` files lying around I have to clean up manually...
This PR reverses the patches in a trap, so that patches are reversed even if `bat cache` is aborted with Ctrl + C (or fails for other reasons)
=> assets/create.sh: Reverse patches even if `bat cache` fails or aborts

CHANGELOG.md, src/bin/bat/main.rs, src/syntax_mapping.rs
This will allow us to add new enum variants in the future without breaking
semver compatibility. See
https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute
Since we already added an enum variant since v0.18.3, now is a good time to mark
it as `#[non_exhaustive]`. Even if we currently always bump major version (since we are on 0.x.x) there will come a time when we don't, and then it's nice to have this prepared.
=> Mark `MappingTarget` as `#[non_exhaustive]` for increased semver flexibility

tests/benchmarks/run-benchmarks.sh
I am setting up a new computer and thus are missing a lot of tools. I
noticed we rely on `jq` being installed, which is a bit annoying when it
is not installed yet. That's easy enough to install on Linux, but on a fresh
macOS install it is not trivial to do. Partly because MacOS refuses to run
unsigned software by default.
We can quite easily get rid of this dependency on `jq` by using a simple
`python3` oneliner.
For reference, the dependency on `jq` was added in ea2faf45e4.
If you prefer to keep the `jq` dependency I am fine with that. Personally I
think it's nice to reduce dependencies  on external tools though. Python3 is of course also an external tool, but it is installed by default on both macOS and (practically) all Linux distributions.
(This is the only place we use `jq`)
=> run-benchmarks.sh: Use `python3` oneliner instead of `jq`

src/assets/build_assets/acknowledgements.rs
This license is apparently common enough that GitHub recognizes it. See
https://github.com/dncrews/GraphQL-SublimeText3/blob/master/LICENSE.
This will fix the CI failure in #2000
Just to clarify: the license text will not be part of the acknowledgments output (same as the other public domain license)
=> Allow the license used by GraphQL

rustfmt.toml
Having an empty `rustfmt.toml` in the repository causes rustfmt to ignore users' global settings and ensures formatting consistency. See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#configuring-rustfmt
=> Add `rustfmt.toml`

CHANGELOG.md, src/printer.rs, tests/integration_tests.rs
Hey 👋 
I have attempted to fix this in two ways: the [first commit](https://github.com/sharkdp/bat/pull/1985/commits/129210e9fa181c06409d5ad085a0b0744cc5fb1d) is a simple, ANSI-specific condition.
The [second commit](https://github.com/sharkdp/bat/pull/1985/commits/31404f6a172c74936481189fec58e0ec05975efd) is using a custom scope to allow each theme to customise how the highlighted line's font style is set.
Let me know what you think and I can squash to a single final commit.
Fixes #1730
=> Underline highlighted lines in ANSI theme

CHANGELOG.md, assets/completions/bat.bash.in
Issue #2066 reports that bash completion is broken on macOS. This is because the version of `bash-completion` that's often packed on macOS via Home-brew is v1.3, which doesn't include the missing `_init_completion` function.
This PR adopts a pattern seen across many other projects (e.g. `tmux`/ `gh` / `kubectl` /  `helm`, some of which use the Cobra Go library to [autogenerate their completion](https://github.com/spf13/cobra/blob/master/bash_completionsV2.go#L32-L38)) to add a shim function with the minimal required functionality.
Completion now works for me on both macOS 10.15.7 and Ubuntu 22.04.
=> fix Bash completion on macOS

doc/README-ja.md, doc/README-ru.md
`https://repology.org/project/bat/` doesn't exist now.
=> Fix a repology badge in READMEs

CHANGELOG.md, src/bin/bat/main.rs
Could not read contents of '/Users/martin/.cache/bat/metadata.yaml': No such file or directory (os error 2).
```
---
bat_version: 0.20.0
creation_time:
secs_since_epoch: 1646283165
nanos_since_epoch: 208676000
```
When we have access to https://github.com/sharkdp/bugreport/pull/11 we will be able to get even more info for custom assets, but the metadata is a significant giver of valuable information by itself that we can add already now to `bat`, so let's do that.
This will help slightly with https://github.com/sharkdp/bat/issues/2085
=> Include contents of custom assets `metadata.yaml` in `--diagnostics`

CHANGELOG.md, src/pretty_printer.rs
This PR allows crates using `bat` as a library to configure the `show_nonprintable` setting via the `PrettyPrinter` API.
Note that it is possible to use `bat` as a lib and configure this, but the workaround requires using `bat`'s "inner" API which is discouraged by `bat`'s documentation.
Current workaround:
```rs
let mut config = bat::config::Config::default();
config.show_nonprintable = true;
let assets = bat::assets::HighlightingAssets::from_binary();
let ctrl = bat::controller::Controller::new(&config, &assets);
let inp = bat::input::Input::from(bat::Input::from_bytes(&output));
ctrl.run(vec![inp]).unwrap();
```
Once this PR is merged, consumers will be able to do this:
```rs
bat::PrettyPrinter::new()
.input_from_bytes(&output)
.show_nonprintable(true)
.print()
.expect("Failed to print …
```
=> Allow configuring show_nonprintable from PrettyPrinter

CHANGELOG.md, Cargo.toml
Cargo.lock already specifies 1.5.5, but we should also do it in Cargo.toml.
I forgot that in #2139.
For #2125
=> Lock regex crate at min 1.5.5 for CVE-2022-24713

CHANGELOG.md, Cargo.lock, Cargo.toml, src/bin/bat/main.rs
It will look like this:
```
- metadata.yaml, 100 bytes
- syntaxes.bin, 726649 bytes
- themes.bin, 40475 bytes
```
or this:
```
'/Users/martin/.cache/bat' is empty
```
or this:
```
'/Users/martin/.cache/bat' not found
```
=> Print info about custom assets in --diagnostics

.github/ISSUE_TEMPLATE/bug_report.md
Well, to be fair, only the `/usr/.crates2.json` one at the moment. But we can add more later.
Also explicitly ask for steps on how to reproduce the reported bug.
=> bug_report.md template: Mention some already reported bugs

CHANGELOG.md, src/syntax_mapping.rs
`/var/spool/mail` and `/var/mail` are often symlinked, but not necessarily so (https://serverfault.com/a/351783/549727). So I mapped both.
=> Add mapping for Unix mail spool

src/bin/bat/config.rs, src/input.rs
Clippy in the newly released Rust 1.60 found some new lints.
Conveniently, all of them were fixable with `--fix`.
By fixing these lints it becomes easier for us and others to see when
new lints are introduced.
=> Run `cargo clippy --fix --all-targets --all-features` with Rust 1.60

src/printer.rs
We do this to only have one invocation of `highlighter.highlight(...)`
so we don't need to change to `highlighter.highlight_line(...)` in two
places in #2181.
=> printer.rs: De-duplicate code to highlight long lines

README.md
The change emits the absolute path from root for changed files so one does not need to be in the repo root for `batdiff` to work, anywhere within the repo is fine.
```
$ git diff --name-only --diff-filter=d
gcp/terraform/apps/platform/sum/main.tf
gcp/terraform/apps/platform/sum/prd.tfvars
```
vs
```
$ git diff --name-only --relative --diff-filter=d 
main.tf
uat.tfvars
```
=> Add `--relative` to `batdiff` in README.md

.github/workflows/CICD.yml, doc/release-checklist.md
Note that we run `find . -name bat.1` before we run anything with
`--all-features`, because `--all-features` is considered a separate
target, and so we will get a different (but identical) `bat.1`. For
example, we might have these:
./target/debug/build/bat-218e9538b4996215/out/assets/manual/bat.1
./target/debug/build/bat-89d6f56802af023f/out/assets/manual/bat.1
By showing the man page earlier, there is only one `bat.1` to pick from.
=> Simplify release-checklist.md by printing `-h`, `--help` and `man` in CI

doc/release-checklist.md
Using `--allow-dirty` increases the risk of the published code not being versioned properly in git, so stop recommending it.
Recommend `--locked` for `cargo install` so that the command will not fail if you are using the MSRV toolchain and the latest version of a dependency happens to have a higher MSRV than we do. Contrary to e.g. `cargo build`, `cargo install` will not default to versions in `Cargo.lock`, but instead try to use the latest compatible versions of everything, unless `--locked` is passed.
Recommend a single `git grep` command for MSRV that filters out irrelevant hits in `CHANGELOG.md` and `tests/`.
This is in preparation of the v0.21.0 release so that the diff becomes smaller when it is time to make the release for real.
=> Tweak release-checklist.md

CHANGELOG.md, assets/syntaxes/02_Extra/INI.sublime-syntax, tests/syntax-tests/highlighted/INI/test.inf, tests/syntax-tests/source/INI/test.inf
I discovered this while debugging an unexpected diff of `assets/syntaxes.bin` for the upcoming v0.21.0 release.
We need to type `inf` and `INF` as strings in `INI.sublime-syntax`,
otherwise `yaml-rust` interprets them as real numbers ("infinity") and
they do not get registered as file extensions:
/Users/martin/src/yaml-rust # https://github.com/chyh1990/yaml-rust
% cargo run --example dump_yaml ~/src/bat/assets/syntaxes/02_Extra/INI.sublime-syntax
---
String("name"):
String("INI")
String("file_extensions"):
String("ini")
String("INI")
Real("inf")        <--- NOTE: Interpreted as real number
Real("INF")
...
Also add a regression test.
=> Make `INI` syntax register as handler of `.inf` files

.github/workflows/CICD.yml, CHANGELOG.md
The Docker images used by `cross` use very old versions of glibc, so we can simply "cross" compile to fix #2106.
Before (binary from a recent master build):
```
▶ objdump -T bat|rg 'GLIBC_2.[0-9][0-9]'      
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.29) log
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.18) __cxa_thread_atexit_impl
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.25) getrandom
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.15) posix_spawnp
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.28) statx
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.29) posix_spawn_file_actions_addchdir_np
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.17) clock_gettime
0000000000000000      DF *UND*	0000000000000000 …
```
=> Relax glibc requirements on x86_64-unknown-linux-gnu

CHANGELOG.md, src/pager.rs
Used rsamuelklatchko's suggested changes to fix recursive fork issue. Fixes issue #2023.
=> Prevent fork nightmare with PAGER=batcat

CHANGELOG.md, src/bin/bat/clap_app.rs, tests/integration_tests.rs
Part of fix for #2128 
Makes the -P ~and -pp~ option take precedence over --paging when given. See issue for more details 🙂  Had to change one test, as it assumed the opposite of what the issue is explaining.
=> Make `--no-paging`/`-P` override `--paging=...` if passed as a later arg

CHANGELOG.md, assets/completions/bat.fish.in
Back in 2020, the command-line completions for bat that had been shipping with fish were removed in favour of the completions file that currently ships with bat (see discussion in #651). Unfortunately, the [deprecated fish completions](https://github.com/fish-shell/fish-shell/blob/ea8a2b2/share/completions/bat.fish) had some nifty features that weren't carried over. This PR restores those features and expands upon them.
Improvements vs. the current completions:
- Less verbose descriptions → better columned layout.
- Notably, default options (e.g. `always`, `auto`) are indicated in the option-completion text, not the description of the option itself.
- Supports all documented options, including those for `bat cache`.
- Fully (!) supports completing `bat --map-syntax <glob …
=> better fish completions

CHANGELOG.md, src/lib.rs, src/pretty_printer.rs, tests/test_pretty_printer.rs
We can't keep `syntect::parsing::SyntaxReference` as part of the public API, because that might prevent us from bumping to syntect 6.0.0 without also bumping bat to v2.0.0.
So introduce a new stripped down struct `Syntax` and return that instead. Let it be fully owned to make the API simple. It is not going to be in a hot code path anyway.
I have looked at all code of our 27 dependents but I can't find a single instance of this method being used, so this change should be safe for v1.0.0. It is only used in our own example code as far as I can tell.
For reference (mostly to my future self), here is the script I used to download the code of all dependents. Then one can grep around in the code of dependents:
```bash
#/usr/bin/env bash
bat_dependents="
barberousse
borrowing_exerci
bropages …
```
=> Make `bat::PrettyPrinter::syntaxes()` iterate over new `bat::Syntax` struct

Cargo.lock, Cargo.toml, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/bin/bat/main.rs
This updates to clap v3 and resolves all deprecations as of right now.
I mostly relied on the tests.
Help output has two main changes that I noticed
- The sections are no "Args", "Options", "Subcommands"
- The text for `--version` is slightly different
I was confused as to why external subcommand support was enabled but I left it.
Some potential further changes
- Preserve parsed values (like numbers) rather than using strings
- Switch lists of possible values to implementing or deriving the `ValueEnum` trait on enums
- Switching to the derive
Fixes #2056
=> refactor: Migrate to clap 3

assets/syntaxes/02_Extra/log.sublime-syntax
Update the log syntax definition to allow color schemes to color entire lines differently based on log level.
Addresses #2152
=> Syntax: [Log] scope whole line based on log level

src/assets/assets_metadata.rs, src/assets/build_assets/acknowledgements.rs, src/bin/bat/main.rs, src/less.rs, src/line_range.rs, src/paging.rs, src/preprocessor.rs, src/syntax_mapping.rs
For rationale on the `s.push_str(&format!(…))` => `write!(s, …)` changes, see https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string (TLDR: it saves one allocation). This leads to a ~15% performance improvements for `bat -A` in cases where there are a lot of non-ASCII characters:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./bat-master --no-config -A ./bat-master` | 259.8 ± 1.1 | 258.4 | 261.7 | 1.15 ± 0.01 |
| `./bat-2301 --no-config -A ./bat-master` | 225.6 ± 1.8 | 224.0 | 229.5 | 1.00 |
=> Fix clippy suggestions

examples/list_syntaxes_and_themes.rs
[`examples/list_syntaxes_and_themes.rs`](https://github.com/sharkdp/bat/blob/113276a62bb5c1658ef9e26954e9b3e0a2543bad/examples/list_syntaxes_and_themes.rs) currently says:
```rust
/// A simple program that prints its own source code using the bat library
```
but it does not do that ([`examples/simple.rs`](https://github.com/sharkdp/bat/blob/113276a62bb5c1658ef9e26954e9b3e0a2543bad/examples/simple.rs) does, I assume it was copied accidentally). I corrected the comment to say:
```rust
/// A simple program that lists all supported syntaxes and themes.
```
=> Correct doc comment for `list_syntaxes_and_themes` example

CHANGELOG.md, src/pretty_printer.rs
Fixes #1919
With this API, the code written in #1919 can be improved as follows:
```rust
use bat::PrettyPrinter;
let targets: (PathBuf, Vec<(usize, usize)>) = vec![];
let mut pp = PrettyPrinter::new();
for (path, ranges) in targets.iter() {
pp.input_file(path);
for (start, end) in ranges.iter() {
pp.highlight_range(*start, *end);
}
pp.print().unwrap();
// Clear highlights for next iteration
pp.clear_highlights();
}
```
=> Add `bat::PrettyPrinter::clear_highlights`

assets/completions/bat.bash.in
See individual commits for details.
=> bash completion improvements

doc/README-ja.md
This PR updates the distribution information and the package URLs.
Old|New
---|---
Ubuntu Eoan 19.10+ or Debian sid|Ubuntu Focal 20.04+ or Debian 11+ (Since Aug 2021)
`https://packages.ubuntu.com/eoan/bat` (not available)|`https://packages.ubuntu.com/search?keywords=bat&exact=1`
`https://packages.debian.org/sid/bat`|`https://packages.debian.org/bullseye/bat`
=> ja: Update description about Debian/Ubuntu packages

.github/workflows/CICD.yml
Upgrades `actions/checkout` to `v3` in `.github/workflows/CICD.yml`
=> ci(CICD.yml): upgrade actions/checkout to v3

README.md
MacOS and Linux bat Homebrew package info are on same page.
=> Updated Homebrew link

assets/syntaxes/02_Extra/VimHelp.sublime-syntax, assets/syntaxes/02_Extra/syntax_test_helphelp.txt, tests/syntax-tests/highlighted/VimHelp/helphelp.txt, tests/syntax-tests/source/VimHelp/helphelp.txt
=> Add VimHelp.sublime-syntax and its test

CHANGELOG.md, src/bin/bat/assets.rs, src/bin/bat/main.rs, tests/integration_tests.rs
=> Fix `bat cache --clear` not clearing the `--target` dir if specified

CHANGELOG.md, tests/syntax-tests/highlighted/cmd-help/test.cmd-help, tests/syntax-tests/source/cmd-help/test.cmd-help
This update includes an overhaul of scope names to better support the set of themes included with bat.
You can find a visual diff for every theme in this PR: https://github.com/victor-gp/cmd-help-sublime-syntax/pull/17
This PR updates the cmd-help syntax test because the scopes (-> colors) have changed.
This PR supersedes #2409.
=> Bump cmd-help syntax to 9b25682

CHANGELOG.md, assets/completions/_bat.ps1.in, assets/completions/bat.bash.in, assets/completions/bat.fish.in, assets/completions/bat.zsh.in
See https://github.com/sharkdp/bat/issues/2085#issuecomment-1271646802.
TLDR: autocompleting the `cache` subcommand causes usability issues. This PR disables it.
I am not terribly familiar with completion scripts TBH. If you are more competent please help check my edits, thanks.
=> Disable completion of `cache` subcommand

src/assets.rs
This PR fixes the code fence in doc comment. This broke syntax highlighting when editing this file in Vim.
=> Fix code fence in doc comment

.github/workflows/CICD.yml, Cargo.lock, Cargo.toml, doc/long-help.txt, doc/release-checklist.md, doc/short-help.txt, tests/integration_tests.rs
From now on (if this PR is merged), any changes to the help texts will be visible in PR diffs, which will make it very easy to review, and very hard to accidentally miss changes to help texts.
If a contributor makes a change to help texts, the `cargo test` failure text they will see contains instructions on how to update the blessed help texts:
error: expect test failed
--> ../doc/long-help.txt
You can update all `expect!` tests by running:
env UPDATE_EXPECT=1 cargo test
In short, to update blessed help texts, one simply does
UPDATE_EXPECT=1 cargo test
Do not run the tests if the `git` feature is missing, since then `--diff` will be missing from `--help`. And do not run the tests on Windows, because then the help text will contain the term `.exe`.
Move `man` page step to after `cargo doc` …
=> Require changes to `-h` and `--help` to be blessed

assets/patches/TwoDark.tmTheme.patch
Adds JSON key highlight fixes for TwoDark theme.
Before:
After:
=> add json key highlighting patch for twodark

CHANGELOG.md, Cargo.lock, Cargo.toml, src/assets.rs
Follows on https://github.com/sharkdp/bat/pull/2197 by improving the implementation of `macos_dark_mode_active`.
For reference there are a lot of ways to read preferences on macOS. Here's the 4 I know of:
1. `defaults` CLI
2. NSUserDefaults via Objective-C
3. CFPreferences via CoreFoundation (C/C++)
4. Directly reading and parsing the file from disk
Out of all of these, `defaults` is the slowest because it involves spawning and executing a whole separate executable to read one value. `defaults` is implemented via 2, which is implemented via 3 at the end. In order to speed this up, I just used option 4 as `bat`'s needs are fairly simple. Using `CFPreferences` would have also worked but the use of `#![deny(unsafe_code)]` indicated that would have been in conflict with the crate's goals …
=> Directly read macOS theme preference instead of using defaults

CHANGELOG.md, assets/syntaxes/02_Extra/Manpage.sublime-syntax, assets/syntaxes/02_Extra/syntax_test_man.man, tests/syntax-tests/highlighted/Manpage/bat-0.16.man, tests/syntax-tests/highlighted/Manpage/fzf-0.33.0.man, tests/syntax-tests/highlighted/Manpage/sway.5.man, tests/syntax-tests/source/Manpage/sway.5.man
=> Scope environment variable and commands sections in Manpages

.github/workflows/CICD.yml
This PR fixes all current deprecation warnings by the build jobs.
The unmaintained `actions-rs/*` actions are replaced with [`dtolnay/rust-toolchain`],
[`taiki-e/install-action`] and plain cargo commands.
The deprecated `set-output` command is replaced by writing the output variables into a file. 
See [announcement].
```bash
echo "NAME=${value}" >> $GITHUB_OUTPUT
```
[`dtolnay/rust-toolchain`]: https://github.com/dtolnay/rust-toolchain
[`taiki-e/install-action`]: https://github.com/taiki-e/install-action
[announcement]: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Replace unmaintained GitHub Actions

.github/workflows/CICD.yml, Cargo.toml
It limits clippy to only warn about lints that are compatible with the current MSRV.
=> Set `rust-version` in Cargo metadata and use it in the MSRV build job

.github/workflows/CICD.yml
With the correct operator, the `bat` package is correctly selected and the `--no-deps` argument can be omitted.
However, without the `--no-deps' argument, cargo must fetch all dependencies.
=> Fix `jq` expression for retrieving `rust-version` in MSRV build job

Cargo.lock, Cargo.toml, src/assets.rs, src/bin/bat/directories.rs
The `dirs` crate was forked as `dirs-next` after the original repos were archived.
The fork hasn't released a new version [since October 2020](https://crates.io/crates/dirs-next/versions), while the original has been taken off the shelf and has seen updates since then.
A [new version](https://crates.io/crates/dirs/5.0.0) was released just some days ago, switching from `winapi` to `windows-sys`.
=> Replace `dirs-next` with the original `dirs` crate

CHANGELOG.md, src/pretty_printer.rs
=> Make `PrettyPrinter::header` an alias for `header_filename`

CHANGELOG.md, build.rs
Makes packaging easier, e.g. by doing `export BAT_ASSETS_GEN_DIR=${PWD}/gen` instead of looking in the target dir.
=> Allow customizing output directory for generated assets

Cargo.lock, Cargo.toml, src/bin/bat/app.rs
The crate is already used by `clap` and a similar trait is about to be stabilized in `std`.
https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html
=> Use the `is-terminal` crate instead of `atty`

Cargo.lock, Cargo.toml
The version replaced `xml-rs` with the `quick-xml` crate. That makes -1 warning for an unmaintained crate from `cargo audit`.
=> Update `plist` to 1.4

assets/completions/bat.bash.in
"cword" is unset and even is not used in completion for other shells, so it probably shouldn't be here either. If it for some reason should be there add the directive "# shellcheck disable=SC2034" to the line above it.
=> Clean-up bash completion

Cargo.lock, Cargo.toml
The new `clap` version is using the new `anstyle` & `anstream` crates for its ANSI text styling and I want to replace the `nu-ansi-term` crate with `anstyle` in a follow-up PR.
Blog: [`anstream`: simplifying terminal styling](https://epage.github.io/blog/2023/03/anstream-simplifying-terminal-styling/)
=> Update `clap` to 4.2

src/bin/bat/app.rs
This seems to have been introduced in 57cc0d843567eef566540074b391f8212d859871 since the condition `!atty::is(Stream::Stdin)` was inverted to `std::io::stdin().is_terminal()`. This seems to be a mistake since the comment says
```
// If we are reading from stdin, only enable paging if we write to an
// interactive terminal and if we do not *read* from an interactive
// terminal.
```
but the current code enables paging if stdin **is interactive**. 
This PR just flips the condition back to how it was to restore the original behavior. 
No changelog update as there hasn't been a release since the regression was introduced.  
Fixes #2572
=> Fix paging not happening when stdout is interactive but stdin is not

.github/workflows/CICD.yml
This CI check will fail if there are crates with known security vulnerabilities in Cargo.lock.
It will not fail because of warnings. We currently have two warnings:
```console
$ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 543 security advisories (from /home/martin/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (184 crate dependencies)
Crate:     encoding
Version:   0.2.33
Warning:   unmaintained
Title:     `encoding` is unmaintained
Date:      2021-12-05
ID:        RUSTSEC-2021-0153
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0153
Dependency tree:
encoding 0.2.33
└── bat 0.23.0
Crate:     atty
Version:   0.2.14
Warning:   unsound
Title:     Potential unaligned read
Date:      2021-07-04 …
```
=> CICD: Run cargo audit

CHANGELOG.md, src/syntax_mapping.rs
`/etc/os-release` and `/usr/lib/os-release` are files found on basically every Linux distro that describe the OS. As far as I know, there is no other use case for the file name `os-release`.
See https://www.freedesktop.org/software/systemd/man/os-release.html
=> Add `os-release` syntax mapping

CHANGELOG.md, src/syntax_mapping.rs
Adds a syntax mapping to use `Dockerfile` syntax for `Containerfile`s. Based on #2606.
=> Add `Containerfile` syntax mapping

Cargo.lock
Without fix:
$ cargo +nightly build
Compiling proc-macro2 v1.0.54
error[E0635]: unknown feature `proc_macro_span_shrink`
--> /home/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.54/src/lib.rs:92:30
|
92 |     feature(proc_macro_span, proc_macro_span_shrink)
|                              ^^^^^^^^^^^^^^^^^^^^^^
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
=> Cargo.lock: Bump proc-macro2 to fix build with Rust nightly

CHANGELOG.md, src/syntax_mapping.rs
Adds syntax mapping for KSH based on Bourne Again Shell. Solves issue #2633
=> fix for issue #2633

CHANGELOG.md, README.md, src/syntax_mapping.rs
Changed single quotes to double quotes in README.md fzf integration example for better compatibility across platforms. See issue #2095
=> fix for issue #2095

.github/workflows/CICD.yml
This opens up future possibilities:
* GitHub's auto-merge feature that merges a PR once CI passes
* Auto-merge of dependabot PRs that pass CI ([example](https://github.com/Enselic/cargo-public-api/pull/425))
But before we do any of that we need to have this new job merged for a while to see that it works also in bat's CI setup. In other words, we need to check that it only pass if all other jobs pass, and fails otherwise.
=> CICD: Add `all-jobs` job

src/syntax_mapping.rs
This PR fixes #2535
It adds a syntax mapping that treats `.jsonl` files as `JSON` in terms of syntax highlighting.
=> fix: Add syntax mapping `*.jsonl` => `json`

README.md
As WinGet gets more common and included in newer Windows 10/11 builds, I think it deserves a mention it in the installation methods.
=> feat: describe WinGet method for Windows install

CHANGELOG.md, README.md, src/syntax_mapping.rs
Add a mapping to use `Rust` for rusty object notation, identified by `.ron` extension. See [#2427](https://github.com/sharkdp/bat/issues/2427).
=> Add `*.ron` syntax mapping

CHANGELOG.md, doc/long-help.txt, src/bin/bat/clap_app.rs, src/bin/bat/config.rs, src/bin/bat/main.rs, tests/integration_tests.rs
=> Add environment variable `BAT_PAGING`

.github/workflows/CICD.yml, README.md
- Resolves #1102
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
**Before merging this:** Please follow the instructions at https://github.com/sharkdp/hyperfine/pull/622. It also applies here.
=> Add Winget Releaser workflow

src/syntax_mapping.rs
address #2643 
did a mistake on the other PR, but this adds the test to ensure there aren't duplicates. The test will show any instances of the first duplicated key found.
There's also a change to ensure that duplicate paths to git config directories aren't added - still allows for two different directories.
=> No duplicate keys test, fixes #2643

Cargo.lock, Cargo.toml, src/printer.rs
bat depends on `encoding` crate but it is [no longer maintained](https://github.com/lifthrasiir/rust-encoding/issues/127). This is reported as [RUSTSEC-2021-0153](https://rustsec.org/advisories/RUSTSEC-2021-0153) in the advisory DB. The advisory suggests [`encoding_rs` crate](https://crates.io/crates/encoding_rs) as alternative.
This PR replaces the unmaintained crate with the alternative.
As a side effect, this patch makes bat's UTF16 support a bit more efficient:
- Decoding with UTF16LE or UTF16BE is now handled with `Cow` instead of `String`. It means that it can avoid extra allocation by reusing the original string buffer when no character in the buffer was replaced while encoding.
- Removing BOM is now handled by `encoding_rs` more efficiently thanks to …
=> Replace unmaintained `encoding` dependency with `encoding_rs`

examples/buffer.rs, src/bin/bat/main.rs, src/controller.rs, src/error.rs, src/pretty_printer.rs, src/printer.rs
Following on from my comment in #956, this PR adds the ability to write output to a `std::fmt` buffer instead of stdout. It does this by changing the `handle` used by the printer to be a mutable reference to either one of `dyn fmt::Write` or `dyn io::Write`.
Included is also an added example to show that it works. I didn't add it to the `PrettyPrinter` but I can do if it seems like a good idea.
Anything else let me know!
=> feat: Optionally write to a buffer instead of stdout

Cargo.lock, Cargo.toml, src/assets.rs, src/bin/bat/directories.rs
The cache & config paths are unchanged. The `etcetera` crate allows you to use the XDG spec on macOS too without any hassle. In addition, it is slightly smaller.
Disclaimer: I've recently become a maintainer of the `etcetera` crate. AFAIK, it is the only crate that can replace this logic.
=> Replace `dirs` crate with `etcetera` crate

CHANGELOG.md, Cargo.lock, Cargo.toml, assets/completions/_bat.ps1.in, assets/completions/bat.zsh.in, assets/manual/bat.1.in, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/controller.rs, src/error.rs, src/input.rs, src/lessopen.rs, src/lib.rs, tests/integration_tests.rs, tests/utils/command.rs
Addresses #1739 and offers an alternative to #1597.
This pull request adds support for `$LESSOPEN` and `$LESSCLOSE` to `bat`. I tried to be as compatible with `less`'s implementation as I could, and I tried to make sure it could handle each of the cases outlined in the "Input Preprocessor' section of `less`'s `man` page. These cases are:
- `$LESSOPEN` writing output to a temporary file that gets cleaned up by `$LESSCLOSE`
- `$LESSOPEN` directly piping data and using empty output to signal to fall back to the original file
- `$LESSOPEN` directly piping data and using the exit code to determine whether or not to fall back to the original file
- The previous two cases, but also with `$LESSCLOSE`
- All of the above cases, but reading from stdin instead of a file
Basically, the `$LESSOPEN` …
=> Add `$LESSOPEN` and `$LESSCLOSE` support

tests/integration_tests.rs
Fix the `no_args_doesnt_break` test to avoid calling `from_raw_fd` twice on the same raw file descriptor, as that cause the file descriptor to be closed twice, which means it could accidentally close some unrelated newly created file descriptor.
=> Fix a double-`close` in the `no_args_doesnt_break` test.

README.md
Removes duplicate winget instructions for Windows install.
=> [docs] Remove duplicate winget

tests/syntax-tests/create_highlighted_versions.py
I'm setting 'Auto' appearance mode in the OS settings. It automatically sets the light mode during the daytime and switches to the dark mode at night.
Since syntax tests use `default` theme, bat automatically switches the default color theme looking at the OS settings on macOS. However syntax tests assume the theme is always dark. So the tests fail during the daytime in my environment.
This PR fixes the issue by setting `Monokai Extended` (which is the default color theme in dark mode) explicitly.
=> Fix syntax tests failure on macOS during the daytime

CHANGELOG.md, src/syntax_mapping.rs
[SARIF](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html) is a format for reporting static analysis results. It is [used by GitHub CodeQL](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning?learn=code_security_integration&learnProduct=code-security) for example.
Here are some samples from Microsoft's VSCode extension:
https://github.com/microsoft/sarif-vscode-extension/tree/main/samples
The SARIF format is built on top of JSON so the `.sarif` files can be highlighted as JSON. This PR adds support for the file extension.
=> Associate `*.sarif` files with `json` syntax

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/yaml.rs
=> Updated version of `serde_yaml` to 0.9

CHANGELOG.md, src/line_range.rs
=> Fix arithmetic overflow in `LineRange::parse_range`

CHANGELOG.md
Updated by drafting a v0.24.0 release and clicking "Generate release notes", and then check what CHANGELOG.md was missing.
=> Update CHANGELOG.md for v0.24.0

tests/github-actions.rs
At first I thought we had forgot the `winget` job , but since that is only used for release, I don't think we want that in `all-jobs` (which we later can use as "required to pass before auto-merge will merge"). Add a test to check we do not forget future jobs though.
=> Add test for what jobs 'all-jobs' references

.github/workflows/Auto-merge-dependabot-PRs.yml
I have been using this myself in cargo-public-api, and what we have here is the result of several iterations, and this has worked well for quite some time now.
To activate this, we need to:
* Go to https://github.com/sharkdp/bat/settings/branches (only you can do this sharkdp)
* Click 'Edit' for 'master'
* Check 'Require status checks to pass before merging'
* Check 'Require branches to be up to date before merging'
* For 'Status checks that are required.', add 'all-jobs'
* Create a token for a bot-user. We can use @EnselicCICD, or maybe you sharkdp can create your own account. GitHub ToS explicitly allows one machine-account per user last time I checked.
* Add that user as a collaborator to this repo (only you can do this sharkdp).
Maintainers will still be able to push directly to main. …
=> Setup auto-merge of dependabot PRs that pass CI

.github/dependabot.yml
So we can more easily test that dependabot auto-merge works as it should. Once we have confirmed it does, we revert this commit.
=> Temporarily change dependabot to daily

.github/dependabot.yml
Reverts sharkdp/bat#2714
Auto-merge seems to work sufficiently well now.
=> Revert "Temporarily change dependabot to daily"

CHANGELOG.md, Cargo.toml
The MSRV is already 1.70 anyway, so this has no effect on compatibility.
=> Bump edition to 2021

Cargo.lock, Cargo.toml, build.rs, build/application.rs, build/main.rs, build/util.rs
The original intent behind this PR is to accommodate for #2747 (PR: #2755), which requires significant code additional to the build script. Hence it would make sense to clean up the build script beforehand and make it organizationally amenable to said addition (i.e. splitting the code into multiple files and modules). There should be no functional changes.
While doing so, I also did some maintenance work:
- cleaned out the old compgen code that's unlikely to ever be used again
- use `anyhow` to make life a bit easier
- fix inaccurate use of the `option_env!` and `env!` macros (the environment variables should be read at build script run time, not build script compile time)
- use newer code style, specifically
- implicit variable capture in format string ([since …
=> Build script refactor

.github/workflows/require-changelog-for-PRs.yml, CHANGELOG.md
This workflow ensures that every PR has a corresponding entry in CHANGELOG.md that includes the PR number and the submitter ID.
=> CI: add changelog check

assets/completions/bat.fish.in
=> fix(completions): add missing fish completions

CHANGELOG.md, tests/benchmarks/run-benchmarks.sh
The default run count of 10 was insufficient to stabilise results on my box. So I made the script more easily customisable.
Now you can do this: `RUN_COUNT=50 ./run-benchmarks.sh --release`
=> Minor benchmark script improvements

README.md, doc/README-ja.md, doc/README-ko.md, doc/README-ru.md, doc/README-zh.md
`bat` is already in a lot of no-longer-supported package repos, and that will only continue growing over time. Might as well not display them on the repology badge
_A side-by-side_
| `master` | `?exclude_unsupported=1` |
| ---: | :--- |
| [![Packaging status](https://repology.org/badge/vertical-allrepos/bat-cat.svg)](https://repology.org/project/bat-cat/versions) | [![Packaging status](https://repology.org/badge/vertical-allrepos/bat-cat.svg?exclude_unsupported=1)](https://repology.org/project/bat-cat/versions) |
=> Consider adding `?exclude_unsupported=1` to repology badge

CHANGELOG.md, assets/completions/bat.zsh.in
* Use correct return status so that approximate completion isn't broken. Zsh completions should not return 0 if they fail to add matches. Supporting this typically involves a local variable named `ret` as in the patch. Someone was complaining on a forum about this not working which is what motivated me to take a look 
* Follow zsh conventions on description forms. Not using capitalisation is the convention going back a long time and most people agree that consistency is more important than any preference one way or another. There was also some things which look like copy-paste from help output. We don't put types in angle brackets, e.g. <mode> - users can configure that if they like it and references to something like N only make sense in help output where N also appears in a syntax …
=> Improvements and fixes to zsh completion

CHANGELOG.md, README.md, doc/README-ja.md, doc/README-ko.md, doc/README-ru.md, doc/README-zh.md
=> Update Arch Linux package URL in README files

.github/workflows/CICD.yml, CHANGELOG.md
New values taken from
dpkg-architecture -L
This should fix the recent CI failures. CI recently started to fail with "Debian package already uploaded", seemingly because the musl and non-musl versions had the same name.
=> Use proper Architecture for Debian packages built for musl

CHANGELOG.md, Cargo.lock, Cargo.toml
Serde_yaml 0.9.28+ and unsafe-libyaml 0.2.10+ fixes https://rustsec.org/advisories/RUSTSEC-2023-0075.html.
=> Pull in fix for unsafe-libyaml security advisory

CHANGELOG.md, Cargo.lock
Generated by running `cargo update -p git-version`, which picks up https://github.com/fusion-engineering/rust-git-version/pull/20. This was the last crate in bat's dependency graph still pulling in syn v1.
=> Eliminate dependency on syn v1 by updating git-version

CHANGELOG.md, tests/syntax-tests/highlighted/cmd-help/test.cmd-help
Manual update (as opposed to [Dependabot's](https://github.com/sharkdp/bat/pull/2683)) because the highlighting for the test help message has changed. It's all good because it's as intended, an improvement.
See victor-gp/cmd-help-sublime-syntax#23
Before/After (`bat` is colorized in Usage lines):
=> Bump cmd-help syntax to `b150d84`

README.md
I rewrote part of the README to explain when arguments will not be passed to `less` by default, and to describe the purpose of the `-S` option and when it is used.
=> Clarify when/how default args are added to less.

CHANGELOG.md, Cargo.lock, Cargo.toml, build/syntax_mapping.rs, src/assets/assets_metadata.rs, src/assets/lazy_theme_set.rs
This PR pulls in https://github.com/trishume/syntect/pull/511 and https://github.com/niklasmohrin/clircle/pull/12 to improve bat compile time by 20%. (`bat` is on the critical path for `cargo-expand`'s build, so I am interested in this PR because it will speed up `cargo-expand` compilation by the same amount.)
`cargo build --lib --timings`:
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td><img src="https://github.com/sharkdp/bat/assets/1940490/ebc00a86-c961-428f-9de6-1871c71a6f47"></td><td><img src="https://github.com/sharkdp/bat/assets/1940490/2d4b62d0-4a72-429e-a6bd-8d2f82581c14"></td></tr>
</table>
=> Eliminate dependency on serde's "derive" feature

CHANGELOG.md, Cargo.lock
Fixes [RUSTSEC-2024-0013](https://rustsec.org/advisories/RUSTSEC-2024-0013), which will allow the CI checks to pass again.
=> Update git2 dependency

CHANGELOG.md, src/printer.rs, src/vscreen.rs, tests/examples/regression_tests/issue_2541.txt, tests/integration_tests.rs
Fixes #2541 by ~~removing OSC sequences from lines before starting to print them.~~ no longer considering ANSI OSC sequences as visible text.
|<img width="1278" alt="image" src="https://user-images.githubusercontent.com/32112321/232371560-eaa6389a-2ae4-434e-9e90-3f9e8fdf6a72.png">|
|:-:|
|(Left: Fixed, Right: Current version)|
Prior to this change, we don't interpret OSC sequences in any special way. They aren't caught by `console::AnsiCodeIterator`, so the OSC sequences were being treated as visible text.
- When the OSC is printed in full, the terminal would see a valid sequence and hide it. As a consequence, lines would b e wrapped too early.
- When the OSC is broken for line wrapping, the terminal wouldn't see a valid sequence. In this case, it prints both halves of the text on …
=> Treat OSC ANSI Sequences as Invisible Text & Add OSC 8 Support

CHANGELOG.md, src/decorations.rs
Fixes the following:
To look like:
=> Fix off-by-one error in line number continuation

CHANGELOG.md, src/vscreen.rs
This fixes #2185 and adds a unit test to catch regressions.
=> Fix incorrect categorization of ANSI SGR sequences.

CHANGELOG.md, src/syntax_mapping/builtins/common/50-aws-credentials.toml, src/syntax_mapping/builtins/common/50-json.toml
I'm not 100% sure this is where these should be added.
Let me know if I need to move them somewhere else.
=> Added JSONC and aws credentials to the syntax mappings

doc/long-help.txt, src/bin/bat/clap_app.rs
Adds a short note to the help text of `--style` explaining which style components are enabled by default.
=> Document default style components

CHANGELOG.md, build/syntax_mapping.rs
It turns out there is a valid reason for glob rules to contain `{` and `}`. So I relaxed the compile time restriction.
See https://globster.xyz/.
=> Relax syntax mapping rule restrictions to allow brace expansion

CHANGELOG.md, src/syntax_mapping/builtins/linux/50-podman-quadlet.toml
See https://www.redhat.com/sysadmin/quadlet-podman
Queued up after #2865 as this syntax mapping uses brace expansion.
=> Add syntax mapping for podman quadlets

CHANGELOG.md, doc/long-help.txt, doc/short-help.txt, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/pretty_printer.rs, src/printer.rs, tests/examples/empty_lines.txt, tests/integration_tests.rs
Fixes #762
Based on #1441 by @eth-p 
What I did:
- rebased commits of #1441 with slight changes to resolve conflicts
- added the squeeze functionality that had been added to the `InteractivePrinter` in #1441 to the `SimplePrinter` as well
- added integration tests
=> Add `-s`/`--squeeze` and `--squeeze-limit` (based on #1441).

.github/workflows/require-changelog-for-PRs.yml, CONTRIBUTING.md
In PR #2766 ([`bcc2de86`](https://github.com/sharkdp/bat/commit/bcc2de86b47c26ad5393588aaead540e348dfc3c)) a new workflow was added which ensures that the `CHANGELOG` stays up to date and that entries follow a certain format. However, this has led to quite a bit of confusion among contributors (https://github.com/sharkdp/bat/pull/2827#issuecomment-1874709439). For example, the authors of #2827, #2807, #2835 and #2818 had to modify the changelog multiple times to match the requirements.
To solve that, this PR changes CONTRIBUTING.md according to the new format requirements. Also, a note is added to the workflow to point contributors in the right direction.
But I do have a question that I'm myself confused about. The CONTRIBUTING.md states:
> If your contribution changes the behavior of …
=> Change CONTRIBUTING.md according to new changelog requirements

CHANGELOG.md, src/bin/bat/app.rs, src/syntax_mapping.rs
This is a much simpler and unsurprisingly better try than #2836.
Instead of an expensive thread pool, we simply create one simple worker thread to blindly build every builtin glob matcher until completion (or made to stop). Doing this early results in effective parallelization and therefore saves time. This may end up doing more work than strictly necessary, but that's not what we care about.
=> Faster startup by offloading glob matcher building to a worker thread

src/bin/bat/main.rs
- **Sort env vars printed by --diagnostic**
- **Print $TERM with --diagnostic**
I would also like `--diagnostics` to print the current terminal emulator, but I can't find a portable way to do it.
Maybe `readlink "/proc/$(cat /proc/$(echo $$)/stat|cut -d ' ' -f 4)/exe"` for Linux?
=> Print $TERM in --diagnostics

CHANGELOG.md, src/bin/bat/main.rs, tests/integration_tests.rs
The user knows which theme is used by default with `--list-themes` parameter.
This is a partial screenshot of the output:
Only the `config.colored_output` displays the ` (default)` string. I didn't add it in the other case because it's really minimal but I will add it if you want.
=> display which theme is the default one in colored output

CHANGELOG.md, src/bin/bat/main.rs, tests/integration_tests.rs
The previous [PR #2838](https://github.com/sharkdp/bat/pull/2838) shows which theme is the default one in colored output when `--list-themes` argument is used. This PR does the same with not colored output (as suggested by @Enselic ).
The output is:
I think about another commit to refactor the internal of `list_themes()` function (so it should not the squashed with the previous one).
Current code: 
```rust
if config.colored_output {
for theme in assets.themes() {
// display colored theme
// display "Further themes can be installed..."
} else {
for theme in assets.themes() {
// display basic theme
}
}
```
To:
```rust
for theme in assets.themes() {
if config.colored_output {
// display colored theme
} else {
// display basic theme
}
}
if config.colored_output {
// display "Further themes …
```
=> display which theme is the default one in basic output

CHANGELOG.md, src/preprocessor.rs, src/vscreen.rs
This pull request updates `bat`'s tab expansion preprocessing function to use `bat`'s `vscreen::EscapeSequenceOffsetsIterator` instead of `console::AnsiCodeIterator`.
When running against a file with no tabs, there are no observable differences:
And when running against a file[^1] with 34443 tab characters, the difference is negligible:
However, it did trim a little over 16 KiB off the file size:
```bash
stat bat-master target/release/bat -c "%-20n %s"
```
[^1]: Command to create the file: `file fd --glob '*.rs' --exec-batch sh -c 'cat "$@" > lots-of.rs' {} && sed -i "s/    /\t/g" lots-of.rs`
=> Update bat's tab expansion preprocessor to use bat's ANSI escape sequence iterator.

.github/workflows/CICD.yml, CHANGELOG.md
There is an artifact built by CI of my repo: https://github.com/tzq0301/bat/actions/runs/9400304021/artifacts/1574889384 (open this link in a new tab, and it will begin to download)
The output can be worked well in my Debian VM on MacBook Pro (M1), and `file` command shows that it is statically linked:
```bash
$ file ./bat
./bat: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```
=> Support 'statically linked binary' for aarch64 in 'Release' page

CHANGELOG.md, README.md, doc/long-help.txt, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/lib.rs, src/preprocessor.rs, src/pretty_printer.rs, src/printer.rs, tests/integration_tests.rs
This pull request introduces a new `--strip-ansi` option to `bat`.
This option tells `bat` whether to strip ANSI/VT escape sequences from the input file. The following values are supported:
- `always`: Always strip escape sequences.
- `never`: Never strip escape sequences. (default)
- `auto`: Strip escape sequences when printing any language that is *not* "Plain Text".  
This preserves bat's ability to print piped commands (or pre-highlighted files) and keep their existing colors.
No significant difference.
A minor reduction in performance.
No significant difference.
It's certainly an improvement.
The detection part of `--strip-ansi=auto` causes no significant difference when syntax highlighting is used.
*However*, it does add a few milliseconds of startup time when used with …
=> Add option to remove ANSI escape sequences from bat's input.

CHANGELOG.md
=> Update the Protobuf sobmodule in order to add `.textproto` support

CHANGELOG.md, Cargo.lock
Fixes #3043.
This seems to be a regression in the standard library that unfortunately they can do nothing about. See https://github.com/rust-lang/rust/issues/127343.
I'll admit this is the first time I've run into this situation where an added API breaks type inference. Seems like it's an entire category of possible regressions against which the compiler currently has no warning.
=> Bump time to 0.3.36 (fixes #3043)

CHANGELOG.md, src/syntax_mapping/builtins/common/50-json.toml
Fixes #3036.
The `CHANGELOG` diff is just to make that use a more uniform wording (I have NOT changed the "content", other than adding `.jsonld`.
=> Associate JSON-LD `.jsonld` files with `json` syntax

CHANGELOG.md, assets/completions/bat.bash.in, assets/completions/bat.fish.in, assets/completions/bat.zsh.in, assets/manual/bat.1.in
The man page of `bat` (`assets/manual/bat.1.in`) doesn't seem to be up-to-date compared to the output obtained by `bat --help` and the options completed by `assets/completion/bat.bash.in`.
----
Originally reported by https://github.com/akinomyoga/ble.sh/issues/458#issuecomment-2156378867. A Bash interactive setting `ble.sh` extracts the descriptions of the options generated by programmable completions from the man page, but the discrepancy between the programmable completion `assets/completion/bat.bash.in` and the man page `assets/manual/bat.1.in` causes missing descriptions for some options.
However, I still see discrepancies between different files:
- `doc/long-help.txt` and `bat --help`
- `doc/short-help.txt` and `bat -h`
- `assets/completion/bat.bash.in`
- …
=> Update the man page of bat (`assets/manual/bat.1.in`)

CHANGELOG.md, README.md, doc/long-help.txt, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/bin/bat/config.rs, src/style.rs, tests/integration_tests.rs
This commit aims to solve #1032, #1161, #1741, and #2894 by introducing a mechanism for merging the styles specified in the config file, `BAT_STYLE` environment variable, and the `--style` command-line argument.
This does so by treating each `--style` argument as a list of style components, and introducing a new `+` and `-` component prefix (e.g. `+numbers`, `-grid`) that allows `--style` lists to be merged together. When a style list consists only of prefixed components, it will be merged into the list that comes before it. If it contains any non-prefixed components, it will *replace* the list before it instead.
Ultimately, the style lists are merged into a final set of style components roughly following this pseudocode algorithm:
```rust
lists.fold(
init=set(),
|accumulator, list| {
if …
```
=> Merge `--style`s from different places using `+`/`-`

CHANGELOG.md, src/syntax_mapping/builtins/common/50-json.toml
=> Associate GeoJSON `.geojson` files with `json` syntax (fixes #3083)

CHANGELOG.md, src/syntax_mapping/builtins/common/50-markdown.toml
Adds a new syntax mapping, so that `*.mkd` files will get `Markdown` syntax highlighting.
Fixes #3060.
=> Map `*.mkd` files to `Markdown` syntax

src/bin/bat/main.rs, tests/integration_tests.rs
#2937 introduced the `(default)` suffix to the output of `--list-themes`, which breaks completion scripts. This PR tries to solve that by not printing the `(default)` suffix when stdout is piped.
Fixes #3073.
=> Don't output default theme info to piped stdout

CHANGELOG.md, Cargo.lock, Cargo.toml, tests/integration_tests.rs
This supersedes https://github.com/sharkdp/bat/pull/3089 and makes the necessary code changes to compile with nix 0.29. This actually makes it possible to drop the `unsafe` usage, because a `File` can be constructed from `OwnedFd` safely and without failing.
=> Bump nix from 0.26.4 to 0.29

CHANGELOG.md, doc/long-help.txt, doc/short-help.txt, src/bin/bat/app.rs, src/bin/bat/clap_app.rs, src/config.rs, src/lib.rs, src/nonprintable_notation.rs, src/printer.rs, tests/integration_tests.rs
Adds a CLI option called `--binary` which controls how binary content is handled. Possible values:
* `no-printing`: do not print any content from a binary file (default; basically what bat currently does)
* `as-text`: treat the binary as if it was text -> it will get printed as is
Fixes #2974.
Fixes #2709.
=> Allow printing binary content by treating it the same as text

README.md
Resolves #2890
As stated in the issue liked above, the `README.md` makes [changing the default config path](https://github.com/sharkdp/bat?tab=readme-ov-file#configuration-file) a bit confusing when it comes to `BAT_CONFIG_PATH` and `BAT_CONFIG_DIR` variables.
This PR adds a mention about how `BAT_CONFIG_DIR` can be used.
=> 📔 docs: mention `BAT_CONFIG_DIR` in the README

src/syntax_mapping/builtins/unix-family/50-apache.toml
The configuration files of Apache HTTP Server on distros other than Debian and its variants are lived in `/etc/httpd/conf/**/*.conf`, (i.e. any file ends with `.conf` in directory `/etc/httpd`) according to `config.layout` file in httpd's repository and httpd's source packages from multiple distros.
This path should also be added to possible path of *Apache Conf* syntax.
Reference:
- [`config.layout` from `httpd` 2.4](https://github.com/apache/httpd/blob/2.4.x/config.layout#L110)
- [`httpd`'s source package from Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/apache/-/blob/2.4.62-1/arch.layout)\
- [`httpd`'s source package from Fedora](https://src.fedoraproject.org/rpms/httpd/blob/rawhide/f/config.layout)
=> Update syntax mapping for Apache Conf

.github/workflows/CICD.yml
MacOS 12 is deprecated in GitHub Actions and no longer usable
=> Build with MacOS 13 instead of 12

.cargo/audit.toml, .github/workflows/CICD.yml, CHANGELOG.md, Cargo.lock, Cargo.toml
- `cargo audit` failed to run in CI, presumably the `ubuntu-latest` image version changed and no longer has the ``cargo-audit`` crate installed by default
- audit failed due to unsoundness in `anstream`
- upgrading clap to fix that required bumping MSRV from 1.70 to [1.74, released over a year ago](https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html)
=> [CI] fix cargo audit failing to run successfully

CHANGELOG.md, assets/patches/Markdown.sublime-syntax.patch
Updated the Markdown patch file to add support for puppet syntax highlighting in Markdown code snippets, in response to https://github.com/sharkdp/bat/issues/3148.
Behavior before change:
Behavior after change:
=> Added patch for puppet syntax highlighting in Markdown code snippets

CHANGELOG.md, assets/patches/1337.tmTheme.patch, assets/patches/OneHalfDark.tmTheme.patch, assets/patches/TwoDark.tmTheme.patch, assets/themes/ansi.tmTheme, assets/themes/base16-256.tmTheme, assets/themes/base16.tmTheme
=> Patch themes for better manpage syntax highlighting

README.md
This pull request updates the instructions for using `bat` as a MANPAGER.
Specifically,
- It replaces `col` with `sed` (solution C in [#2568](https://github.com/sharkdp/bat/issues/2568#issuecomment-1938232553)).
- And improves instructions for systems that use `mandoc` instead of `man-db`.
#1145
=> Update README steps for using bat as MANPAGER

CHANGELOG.md, Cargo.lock, Cargo.toml
This includes mostly dependency updates. The most significant one is that I removed clircle's dependency on winapi. After this PR, running `cargo update` on bat will remove winapi from the lockfile.
=> Bump clircle to 0.6.1

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lessopen.rs, tests/integration_tests.rs
I replaced the `lessopen` implementation to use a crate called `execute` instead of the currently-used `run_script`. This has the benefit of simplifying the code a little, but more importantly fixes a few weird issues I noticed.
The issues I noticed that these changes fix are:
- [`batpipe`](https://github.com/eth-p/bat-extras/blob/master/doc/batpipe.md) not working right when using `fish` as a shell. Currently, `bat` shows the commands that `batpipe` prints to configure `$LESSOPEN` when you evaluate it in your startup config rather than the preprocessed file output.
- `bat` not showing any output at all when using [`glow`](https://github.com/charmbracelet/glow) to preprocess markdown files.
Edit: [Also appears to fix some known issues with `lessopen`-related integration …
=> Rework `lessopen` implementation to use `execute` crate instead of `run_script`

Cargo.lock, Cargo.toml
Thanks for bat :)
Just bumping `git2` to allow/support latest `libgit2`: https://github.com/rust-lang/git2-rs/commit/68aa1ad420ab0f82277c39d21228eca54c833a2a
Also ran `cargo update` since tests still pass on my machine
=> Bump git2 to 0.20

CHANGELOG.md, src/theme.rs, tests/integration_tests.rs
*this is a bit embarrassing since I'm the person who wrote the code in the first place 😆*
=> Fix name of BAT_THEME_{DARK,LIGHT} env vars

README.md
Fixes copy and paste error, where same option was listed twice, instead of the 2 distinct options of `--theme` for different system appearances.
=> Fix tiny accidental repetition in README.md

CHANGELOG.md, build/syntax_mapping.rs
See https://github.com/rust-lang/cargo/issues/15080. This fixes:
```console
error: failed to run custom build command for `bat v0.25.0`
Caused by:
process didn't exit successfully: `target/debug/build/bat-126fec914d2804b6/build-script-main` (exit status: 1)
--- stdout
cargo:rerun-if-changed=build/
cargo:rerun-if-changed=src/syntax_mapping/builtins/
--- stderr
Error: IO error for operation on src/syntax_mapping/builtins/macos: No such file or directory (os error 2)
Caused by:
No such file or directory (os error 2)
```
=> Work around `cargo vendor` losing syntax_mapping builtins directory

CHANGELOG.md, src/syntax_mapping/builtins/linux/50-paru.toml
Paru is a widely used AUR helper. Most ArchLinux users would at minimum know about it.
=> Add syntax mapping for paru configuration files

CHANGELOG.md, src/bin/bat/main.rs, tests/integration_tests.rs
As described in issue #3188, PR #2896 reintroduced the behaviour described in issue #3073 which had previously been fixed with PR #3075. This PR fixes the issue again.
Fixes #3188.
=> Fix: Don't output default theme info to piped stdout

src/assets.rs, src/assets/build_assets/acknowledgements.rs, src/bin/bat/app.rs, src/controller.rs, src/input.rs, src/lessopen.rs, src/line_range.rs, src/printer.rs, src/style.rs, src/syntax_mapping.rs, src/theme.rs, src/vscreen.rs, tests/github-actions.rs, tests/integration_tests.rs
Fixes warnings of the following clippy lints (which are warn-by-default):
- `style` lints
- [clippy::ptr_arg](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg)
- [clippy::into_iter_on_ref](https://rust-lang.github.io/rust-clippy/master/index.html#into_iter_on_ref)
- [clippy::manual_pattern_char_comparison](https://rust-lang.github.io/rust-clippy/master/index.html#manual_pattern_char_comparison)
- [clippy::legacy_numeric_constants](https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants)
- [clippy::redundant_closure](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure)
- [clippy::unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or)
- …
=> Fix clippy lint warnings

CHANGELOG.md, src/syntax_mapping/builtins/common/50-nix.toml
This PR adds a syntax mapping for `flake.lock`, which is JSON. 
As far as lockfiles go, `flake.lock`s are usually pretty readable and it's not too uncommon to inspect it manually (specifically, to compare hashes and to make sure there aren't multiple copies of the same flake in your flake). Therefore I think it's a worthwhile addition to have by default.
=> Add syntax mapping for `nix`s `flake.lock`

.gitmodules, CHANGELOG.md
Fixes #3198.
Before:
- [Failing Dependabot submodules job](https://github.com/sharkdp/bat/actions/runs/13084738523)
- Fails because it cannot locate the `Javascript (Babel)` submodule (responds 302 then 404): 
<https://api.github.com/repos/sharkdp/bat/contents/assets/syntaxes/02_Extra/JavaScript%20(Babel)?ref=4fc55cfcec44dba3f67bd79cac9ccf64dc18eb08>
- Still failing when the ref is master:
<https://api.github.com/repos/sharkdp/bat/contents/assets/syntaxes/02_Extra/JavaScript%20(Babel)?ref=master>
After renaming to `Javascript_(Babel)`:
- Request for the submodule succeeds (responds 302 then 200):
<https://api.github.com/repos/victor-gp/bat/contents/assets/syntaxes/02_Extra/JavaScript_(Babel)/?ref\=fix-submodules-for-dependabot>
After merging to master:
- The request for the submodule …
=> Rename submodule paths to fix Dependabot submodule updates

CHANGELOG.md, tests/syntax-tests/compare_highlighted_versions.py
I stumbled across https://github.com/sharkdp/bat/pull/3236#issuecomment-2746349454 and wanted to fix it.
For more context, a new language was added but the author forgot to run `update.sh` to add a test fixture for it. This should have caused CI to fail, but it passed. The reason is that the highlighting regression test scripts iterate over existing fixtures, and hence don't catch newly added languages that haven't added a fixture.
=> Make highlight tests fail when new syntaxes don't have fixtures

CHANGELOG.md, examples/buffer.rs, src/bin/bat/app.rs, src/bin/bat/main.rs, src/controller.rs, src/lib.rs, src/output.rs, src/pretty_printer.rs, src/printer.rs
This allows to use `--list-themes` with paging by passing all theme sample outputs to the pager as a whole.
Alternative to #3238
(Closes #3238)
=> Add paging to `--list-themes`

.github/workflows/CICD.yml, .github/workflows/require-changelog-for-PRs.yml, CHANGELOG.md
Let's not build for platforms that are broken. If someone fixes the build we can of course add it back later.
=> CICD: Stop building for x86_64-pc-windows-gnu which fails

Cargo.toml
To the best of my knowledge our current MSRV rule is that we can bump MSRV whenever there is a reason for it. Let's document it.
Downstream packagers seem to agree: https://github.com/sharkdp/bat/pull/3216#issuecomment-2781035085
=> Cargo.toml: Document that MSRV can be bumped if there is a reason for it

CHANGELOG.md, Cargo.lock, Cargo.toml, src/printer.rs, tests/integration_tests.rs
Partial fix for #3230.
Bat will no longer crash when multibyte characters are in the file path. However, there may still be misformatting of the header in the output.
=> Fix for multibyte characters in file path

CHANGELOG.md, src/syntax_mapping/builtins/unix-family/50-shell.toml
Fixes #3231, fixes #3145.
Any files named (or with the extensions):
* bashrc
* bash_profile
* bash_login
* bash_logout
* zshrc
* zprofile
* zlogin
* zlogout
* zshenv
Will now be correctly highlighted.
Based off of the recommendation of [this comment](https://github.com/sharkdp/bat/issues/3145#issuecomment-2540502205), but let me know if there's a better way to go about this.
=> Fix syntax highlighting for bash/zsh

.github/workflows/CICD.yml
all PR CI runs are currently failing due to GitHub deprecating the ubuntu-20.04 runner
=> use latest Ubuntu for CI jobs now that GitHub deprecated 20.04

.gitmodules
the repo has gone away, causing all our CI etc. to break
we can keep the highlighting though because we have a .sublime-syntax file
=> remove LiveScript submodule

CHANGELOG.md, README.md, doc/README-ko.md, doc/README-zh.md
Tinted Theming (previously base16-project) is a maintained and community run version of base16: https://github.com/tinted-theming/home/issues/51
A discussion around creating a base16 organization originally took place in 2016 on an issue in the original base16 repo: https://web.archive.org/web/20220603173440/https://github.com/chriskempson/base16/issues/74. The repo was subsequently nuked and most [git history](https://github.com/chriskempson/base16/commits/main/) as well as PRs and issues were destroyed (which is why I linked the web archive version of the issue).
This PR updates the following links:
- `https://github.com/chriskempson/base16` -> `https://github.com/tinted-theming/home`
- `https://github.com/chriskempson/base16/blob/master/styling.md` -> …
=> Update base16 URLs to link to community run version

CHANGELOG.md, src/syntax_mapping/builtins/linux/50-podman-quadlet.toml
It's not really documented, but it turns out that quadlet files placed in any subdirectory of the various search paths will be picked up by podman. This PR updates the matching rules accordingly.
To verify:
```bash
cd /etc/containers/systemd/
mkdir test
cat > test/hello.container <<EOF
[Container]
Image=quay.io/podman/hello
EOF
/usr/lib/systemd/system-generators/podman-system-generator -dryrun
```
You should find that `hello.container` is getting picked up, despite this behaviour not being explicitly mentioned in the man page.
=> Update quadlet syntax mapping rules to cover quadlets in subdirectories

CHANGELOG.md, src/assets.rs
This fix strips the UTF-8 BOM character from the first line before performing syntax detection using `strip_prefix('\u{feff}')`, ensuring that files with BOM are handled correctly.
- Modified `get_first_line_syntax` in `src/assets.rs` to strip BOM before pattern matching
- Added comprehensive test coverage for XML, shell scripts, and PHP files with BOM
- Updated CHANGELOG.md
Fixes #3314
=> Fix UTF-8 BOM file type detection for first-line syntax patterns

.github/workflows/CICD.yml, CHANGELOG.md
CI runs are failing due to `windows-2019` runners being no longer available ([example](https://github.com/sharkdp/bat/actions/runs/16134652467/job/45528489069)). This PR migrates to `windows-2025` runners.
See https://github.com/actions/runner-images/issues/12045
=> CICD: replace windows-2019 runners with windows-2025

CHANGELOG.md, src/error.rs, tests/integration_tests.rs
Resolves #2561
I thought how it can be done better. But the most simple solution for now is this.
The best solution in my opinion is dividing default handle for errors and normal output. But this behaviour will require changing a lot of stuff. 
If this is required - I can do it.
=> Send errors to stderr

assets/manual/bat.1.in
Update man page to include missing information about style specification priority and the behavior of "+" and "-" prefixes when modifying styles. This aligns the man page with the documentation in long-help.txt.
Fixes #3341
=> docs(man): update --style documentation with priority rules

CHANGELOG.md, src/bin/bat/app.rs
An oversight on my part that only came to mind when I'm working on a single core transit VPS today.
=> Only start offload worker thread when there's more than 1 core

README.md, doc/README-ko.md, doc/README-zh.md
Updated documentation for the `git diff` section.
Currently if (for whatever reason) a file in the repo has special characters in its name, including space, new line, etc., batdiff would malfunction. With filenames being handled in form of NULL-terminated strings, the issue is resolved. (delta does not have this problem)
I noticed that this section is not present in Japanese/Russian version of the doc, not sure how to deal with them :P
see also: eth-p/bat-extras#124
=> Update documentation for git diff

README.md
Added note about escaping alias when using help aliasing in zsh
=> Update README.md -- Added info on escaping help aliasing in zsh

CHANGELOG.md, Cargo.lock, Cargo.toml, src/theme.rs
I have finally released version 1.0 of terminal-colorsaurus yesterday 🥳 
There are no behavior changes, only some minor API revisions :)
=> Update terminal-colorsaurus to 1.0

README.md, doc/README-ko.md, doc/README-ru.md, doc/README-zh.md
- Use `-0` instead of `--null` for xargs to work on most systems (e.g., `--null` doesn't work on macOS and OpenBSD);
- Add missing `--relative` and `-z` options for git diff.
=> Make batdiff more portable

assets/completions/_bat.ps1.in
Hi all,
Made an update to the default completion for ps1
1. Removed shortcut entries
Code completion, in powershell, should be more descriptive. 
2. Added completions with individual values for
** Language
** Theme
** Other argument with options
Works with Powershell Core 7
=> Update ps1 completion

assets/syntaxes/02_Extra/Assembly (x86_64).sublime-syntax
* Using ARM Assembly with the bat library works with .language("ARM Assembly"), while x86 has no name. Add name to sublime syntax file.
=> Add x86_64 Assembly to x86 sublime syntax file

.github/workflows/CICD.yml, CHANGELOG.md
Tests and other steps that execute the binary are skipped, because the project is built on an x86_64 Windows host machine and thus can't run arm64 instructions.
Fixes: #2644
=> Add CI build for windows/ARM64

assets/theme_preview.rs, src/assets.rs, src/assets/build_assets.rs, src/bin/bat/assets.rs, src/bin/bat/clap_app.rs, src/bin/bat/config.rs, src/bin/bat/main.rs, src/error.rs, src/input.rs, src/lessopen.rs, src/printer.rs, src/vscreen.rs, tests/tester/mod.rs, tests/utils/mocked_pagers.rs
In a few cases, removed the unneeded `&` - this causes a minor slowdown because compiler cannot eliminate those (yet).
=> inline format arguments

README.md
Closes #3288. I found all of their points reasonable except maybe the last one, which I didn't include documentation for. All changes have only been made to the English `README.md`
=> docs: added minor theming documentation notes

README.md
Adding new installation methods increases risk of supply chain exploits and increases burden of maintainers. Let's put some requirements on what installation methods to have in the README.md
If there is consensus to do this we can close these as "won't fix":
* https://github.com/sharkdp/bat/pull/3374
* https://github.com/sharkdp/bat/pull/2930 (I just now saw I already proposed to close it and there were no objections so I closed it now)
=> README.md: Put some requirements on installation instructions
